'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/engine.js'),B=require('../src/battle.js'),R=require('../src/render.js'),C=require('../src/editor-core.js'),UI=require('../src/battle-ui.js');
const make=(seed='architecture',o={})=>E.generate('battle',seed,o),clone=x=>JSON.parse(JSON.stringify(x));
function edge(s,points){const g=s.gridSize,p=E.center(points),x=p[0]/g,y=p[1]/g,cols=s.battle.cols,v=Math.abs(points[0][0]-points[1][0])<.001;const a=v?[Math.round(x)-1,Math.floor(y)]:[Math.floor(x),Math.round(y)-1],b=v?[a[0]+1,a[1]]:[a[0],a[1]+1];return [a[1]*cols+a[0],b[1]*cols+b[0]].sort((a,b)=>a-b).join(':');}
function valid(s){E.validateScene(s);const b=s.battle,{cols,rows,cells}=b,g=s.gridSize;assert.equal(b.generatorVersion,2);assert.equal(b.diagnostics.requested,b.diagnostics.placed+b.diagnostics.unplaced.length);assert.equal(b.rooms.length,s.features.filter(f=>f.type==='room').length);assert.equal(new Set(b.rooms.map(q=>q.index)).size,b.rooms.length);
 const blocked=new Set(b.partitions.map(p=>edge(s,p))),wet=new Set(b.waterCells),occupied=new Set(),props=s.features.filter(f=>f.battleFootprint);
 for(const f of props){for(const p of f.battleFootprint)assert(E.pointOnOrInside(p,b.boundary,.001),'prop outside envelope');const xs=f.battleFootprint.map(p=>p[0]/g),ys=f.battleFootprint.map(p=>p[1]/g);for(let y=Math.floor(Math.min(...ys)+1e-6);y<Math.ceil(Math.max(...ys)-1e-6);y++)for(let x=Math.floor(Math.min(...xs)+1e-6);x<Math.ceil(Math.max(...xs)-1e-6);x++)occupied.add(y*cols+x);}
 for(const f of s.features.filter(f=>f.type==='portal')){blocked.delete(edge(s,f.points));assert(E.wallSegments(s).some(line=>E.nearPolyline(E.center(f.points),line)<.001),'door is not on a wall');}
 for(let i=0;i<b.rooms.length;i++)for(let j=i+1;j<b.rooms.length;j++){const a=b.rooms[i],c=b.rooms[j];assert(!(a.x<c.x+c.w&&a.x+a.w>c.x&&a.y<c.y+c.h&&a.y+a.h>c.y),'overlapping room allocations');}
 if(B.isRoomless(s.options.theme)){assert.equal(b.rooms.length,0);assert.equal(s.features.filter(f=>f.type==='portal').length,0);assert.equal(E.wallSegments(s).length,0);return;}
 const markers=s.features.filter(f=>f.type==='room'),at=f=>Math.floor(f.y/g)*cols+Math.floor(f.x/g),start=at(markers[0]),seen=new Set([start]),queue=[start];
 for(let k=0;k<queue.length;k++){const u=queue[k],x=u%cols,y=Math.floor(u/cols);for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,yy=y+dy,v=yy*cols+xx;if(xx<0||yy<0||xx>=cols||yy>=rows||!cells[v]||wet.has(v)||occupied.has(v)||seen.has(v)||blocked.has([u,v].sort((a,b)=>a-b).join(':')))continue;seen.add(v);queue.push(v);}}
 for(const f of markers){assert(cells[at(f)],'room in solid');assert(!wet.has(at(f)),'room in water');assert(!occupied.has(at(f)),`${s.options.theme}/${s.seed}/${s.options.cols}x${s.options.rows}: ${f.role} room anchor blocked`);assert(seen.has(at(f)),`${s.options.theme}/${s.seed}: ${f.role} unreachable through doors and dry circulation`);}for(const i of b.circulation)assert(!occupied.has(i),'furniture blocks reserved circulation');
}
test('All encounter defaults produce complete and physically navigable programs',()=>{for(const theme of Object.keys(B.PLANS))for(let seed=0;seed<8;seed++){const s=make('full-'+seed,{theme});assert.equal(s.battle.diagnostics.unplaced.length,0,theme);valid(s);}});
test('Square and hex envelopes, narrow maps and crowded programs retain safe access',()=>{for(const theme of ['dungeon','dwelling','temple','stronghold','sewer','cave','ice-cave','forest','bridge'])for(const mapShape of ['rectangle','hex-flat','hex-pointy'])for(const [cols,rows] of [[16,16],[16,64],[64,16],[48,36]]){const s=make(`${theme}-${cols}-${mapShape}`,{theme,mapShape,cols,rows,entrySide:'north'});valid(s);if(s.battle.diagnostics.unplaced.length)assert(s.battle.diagnostics.warnings.length>0);}});
test('Overflow is indexed and disclosed, preserving the final objective',()=>{const s=make('crowded',{cols:16,rows:16,zones:['entrance',...Array(22).fill('bedroom'),'treasury'],zoneDetails:Array(24).fill({size:'large'})});valid(s);assert(s.battle.diagnostics.unplaced.length>0);assert.equal(s.battle.plan.at(-1),'treasury');assert.deepEqual(s.battle.diagnostics.unplaced.map(q=>q.index).sort((a,b)=>a-b),Array.from({length:24},(_,i)=>i).filter(i=>!s.battle.rooms.some(q=>q.index===i)));});
test('Temples have a processional axis and strongholds a genuine courtyard',()=>{const s=make('axis',{theme:'temple',entrySide:'north'}),b=s.battle,r=Object.fromEntries(b.rooms.map(q=>[q.role,q]));assert.equal(b.diagnostics.layout,'axial');assert.equal(r.narthex.x,r.nave.x);assert.equal(r.altar.x,r.nave.x);assert(r.narthex.y<r.nave.y&&r.nave.y<r.altar.y);assert(b.connections.some(c=>c.kind==='processional'));const k=make('court',{theme:'stronghold',cols:48,rows:40});assert(k.battle.courtyard);assert.equal(k.battle.diagnostics.layout,'courtyard');valid(k);});
test('Households have one stove, one bed per bedchamber, and no arbitrary entrance stairs',()=>{const s=make('household',{theme:'dwelling',cols:48,rows:40,furnishing:1});valid(s);for(const q of s.battle.rooms){const fs=s.features.filter(f=>f.roomKey===q.key&&f.type==='asset');if(q.role==='bedroom')assert.equal(fs.filter(f=>f.asset==='bed').length,1);if(q.role==='kitchen')assert.equal(fs.filter(f=>f.asset==='stove').length,1);if(q.role==='entrance')assert.equal(fs.filter(f=>f.asset==='stairs').length,0);}});
test('Furnishings do not overlap each other or protrude through room walls',()=>{for(const theme of ['dungeon','dwelling','tavern','temple','sewer']){const s=make('furniture-'+theme,{theme}),fs=s.features.filter(f=>f.battleFootprint);for(let i=0;i<fs.length;i++){const f=fs[i],q=s.battle.rooms.find(q=>q.key===f.roomKey);if(q){const p=[[q.x,q.y],[q.x+q.w,q.y],[q.x+q.w,q.y+q.h],[q.x,q.y+q.h]].map(p=>p.map(v=>v*s.gridSize));assert(f.battleFootprint.every(v=>E.pointOnOrInside(v,p,.001)));}for(let j=i+1;j<fs.length;j++)assert(!E.polygonsIntersect(f.battleFootprint,fs[j].battleFootprint),'overlapping props');}}});
test('Natural pools are carved floor, not rock or the reserved passage',()=>{for(let n=0;n<8;n++){const s=make('pool-'+n,{theme:'cave',cols:48,rows:36}),wet=new Set(s.battle.waterCells);for(const i of wet){assert(s.battle.cells[i]);assert(!s.battle.circulation.includes(i));}assert(wet.size>0);valid(s);}});
test('Doors are represented as openings rather than opaque LOS segments in VTT exports',()=>{const s=make('vtt-doors',{theme:'dwelling'}),data=C.vttData(s,100,''),portals=s.features.filter(f=>f.type==='portal');assert.equal(data.portals.length,portals.length);assert(R.render(s).includes('data-battle-walls="architectural"'));for(const p of data.portals){const m=[(p.bounds[0].x+p.bounds[1].x)/2,(p.bounds[0].y+p.bounds[1].y)/2];assert(!data.line_of_sight.some(l=>E.nearPolyline(m,l.map(v=>[v.x,v.y]))<.001),'LOS crosses a door');}});
test('New maps are deterministic, serializable, self-contained and editable',()=>{for(const theme of Object.keys(B.PLANS)){const a=make('stable',{theme}),b=make('stable',{theme});assert.deepEqual(a,b);assert.deepEqual(C.validateAtlas({format:'megamap-atlas',version:1,active:0,maps:[clone(a)]}).maps[0].battle,a.battle);assert(!/NaN|undefined|https?:\/\/(?!www\.w3\.org)/.test(R.render(a)));}const s=make('resize',{theme:'dwelling'}),f=s.features.find(f=>f.battleProp),before=R.render(s);C.scale(f,1.5);assert.notEqual(R.render(s),before);C.rotate(f,90);C.translate(f,3,4);E.validateScene(s);});
test('Density changes furniture, not architecture or door placement',()=>{const a=make('bare',{theme:'dungeon',furnishing:0}),b=make('bare',{theme:'dungeon',furnishing:1}),geometry=s=>s.battle.rooms.map(({featureId,...q})=>q);assert.deepEqual(geometry(a),geometry(b));assert.deepEqual(a.battle.partitions,b.battle.partitions);assert.equal(a.features.filter(f=>f.type==='asset').length,0);assert(b.features.filter(f=>f.type==='asset').length>20);});
test('Legacy floor data still loads and renders without new metadata',()=>{const s=make('legacy');delete s.battle.generatorVersion;delete s.battle.partitions;delete s.battle.surfaces;for(const f of s.features)delete f.battleProp;assert.doesNotThrow(()=>E.validateScene(s));assert.doesNotThrow(()=>R.render(s));});
test('Malformed architectural metadata is rejected on import',()=>{const original=make('unsafe');for(const mutate of [s=>s.battle.partitions=[[[0,0],[NaN,10]]],s=>s.battle.surfaces=[{polygon:[[0,0],[1,1]],material:'stone'}],s=>s.battle.rooms[0].w=Infinity,s=>s.battle.circulation=[-1],s=>s.battle.connections=[{from:{},to:'zone-1',kind:'door'}],s=>s.battle.diagnostics.warnings=[{}],s=>s.features.find(f=>f.battleProp).propWidth=0,s=>s.features.find(f=>f.battleProp).battleFootprint=[[0,0],[1,1]]]){const s=clone(original);mutate(s);assert.throws(()=>E.validateScene(s),/Invalid battle/);}});
test('Reordering, deletion and duplication remap adjacency references to the same rooms',()=>{const o={zones:['entrance','kitchen','pantry','bedroom'],zoneDetails:[{label:'A'},{label:'B',near:2},{label:'C',near:1},{label:'D',near:1}]},m=UI.move(o,1,3);assert.deepEqual(m.zoneDetails.map(d=>d.label),['A','C','D','B']);assert.deepEqual(m.zoneDetails.map(d=>d.near),[null,3,3,1]);assert.deepEqual(UI.remove(o,1).zoneDetails.map(d=>d.near),[null,null,null]);const d=UI.duplicate(o,1);assert.deepEqual(d.zones,['entrance','kitchen','kitchen','pantry','bedroom']);assert.deepEqual(d.zoneDetails.map(d=>d.near),[null,3,3,1,1]);assert.equal(UI.add({zones:Array(24).fill('guest')},'guest').zones.length,24);assert.equal(UI.duplicate({zones:Array(24).fill('guest')},0).zones.length,24);assert.deepEqual(UI.move(o,-1,100).zones,o.zones);});
test('Per-room input normalization preserves safe labels and rejects malformed options',()=>{const o=B.normalize({zones:['entrance','__proto__','kitchen','pantry'],zoneDetails:[{label:'  Front  '},{},{near:3,size:'enormous'},{near:2,access:'root'}]});assert.deepEqual(o.zones,['entrance','kitchen','pantry']);assert.equal(o.zoneDetails[1].near,2);assert.equal(o.zoneDetails[2].near,1);assert.equal(o.zoneDetails[1].size,'auto');assert.equal(o.zoneDetails[0].label,'Front');assert(!UI.render({zones:['entrance'],zoneDetails:[{label:'<img src=x onerror=alert(1)>'}]}).includes('<img'));assert.doesNotThrow(()=>B.normalize(null));});
test('Custom names survive generation and unresolved adjacency preferences are reported',()=>{const s=make('custom-details',{zones:['entrance','kitchen','pantry','bedroom','treasury'],zoneDetails:[{label:'West porch',near:4},{size:'large'},{near:1},{access:'private'},{label:'The safe'}]});valid(s);assert.equal(s.features.find(f=>f.zoneIndex===0).label,'West porch');assert.equal(s.features.find(f=>f.zoneIndex===4).label,'The safe');const d=s.battle.diagnostics;assert(d.unmetAdjacencies.length===0||d.warnings.some(w=>w.includes('Adjacency preferences')));});
test('Painting solid into residential exterior creates visible rock and VTT boundaries',()=>{const s=make('paint-exterior',{theme:'dwelling'}),before=E.wallSegments(s).length,i=s.battle.exterior.find(i=>i%s.battle.cols>1&&Math.floor(i/s.battle.cols)>1);assert(Number.isInteger(i));s.battle.cells[i]=0;assert(E.wallSegments(s).length>before);assert(R.render(s).includes('data-painted-solid="true"'));s.battle.cells[i]=1;assert.equal(E.wallSegments(s).length,before);});
