'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),zlib=require('node:zlib'),fs=require('node:fs'),vm=require('node:vm');
const E=require('../src/engine'),R=require('../src/render'),C=require('../src/editor-core'),B=require('../src/battle'),UI=require('../src/battle-ui'),HQ=require('../src/battle-hq'),M=require('../src/battle-materials');
const make=(o={})=>E.generate('battle','arena-hq-regression',{theme:'arena',...o});
function shape(s){const a=JSON.parse(JSON.stringify(s));delete a.options.hq;delete a.appearance;return a;}
test('Arena is the nineteenth preset, room-free with default-on HQ',()=>{const s=make();assert.equal(Object.keys(B.PLANS).length,19);assert.equal(s.options.theme,'arena');assert.equal(s.options.hq,true);assert.equal(s.appearance.hq,true);assert.equal(s.options.cols,52);assert.equal(s.options.rows,44);assert.equal(s.battle.rooms.length,0);assert.equal(s.battle.arena.coverPlaced,6);assert.equal(s.battle.arena.tiers,4);assert(s.features.some(f=>f.arenaTier));assert(UI.render(s.options).includes('data-arena-preview'));assert(!UI.render(s.options).includes('data-zone-card'));});
test('Arena fits all envelopes, grid orientations, entry rotations and extreme dimensions',()=>{for(const mapShape of ['rectangle','hex-flat','hex-pointy'])for(const gridType of ['square','hex-flat','hex-pointy'])for(const entrySide of ['north','east','south','west'])for(const [cols,rows]of [[16,16],[16,80],[80,16],[52,44]]){const s=make({mapShape,gridType,entrySide,cols,rows,arenaCover:2});E.validateScene(s);assert.equal(s.battle.diagnostics.requested,0);for(const f of s.features)for(const p of f.polygon||f.points||f.battleFootprint||[])assert(E.pointOnOrInside(p,s.battle.boundary,.1),'Outside arena: '+[cols,rows,mapShape,entrySide,f.id]);}});
test('Arena floor and tier controls change scenery, cover zero leaves an empty fighting floor',()=>{const a=make({arenaSurface:'grass',arenaFloor:45,arenaTiers:2,arenaCover:0}),b=make({arenaFloor:75,arenaTiers:5,arenaCover:12});assert.equal(a.features.filter(f=>f.battleProp).length,0);assert.equal(a.features.filter(f=>f.arenaTier).length,16);assert.equal(b.features.filter(f=>f.arenaTier).length,40);assert(E.area(a.battle.arena.floor)<E.area(b.battle.arena.floor));assert.equal(a.options.arenaSurface,'grass');assert.deepEqual(B.normalize({theme:'arena',zones:['entrance','bedroom']}).zones,[]);});
test('Arena barriers export as real walls with both entrances open',()=>{const s=make(),v=C.vttData(s,100,'');assert.equal(v.portals.length,0);assert(v.line_of_sight.length>100);const g=s.gridSize;for(const q of s.battle.arena.entrances){const p=q.map(n=>n/g);assert(!v.line_of_sight.some(l=>E.nearPolyline(p,l.map(p=>[p.x,p.y]))<.4));}assert(!s.features.some(f=>f.type==='room'||f.type==='portal'));});
test('Arena cover is inside the floor, separated and outside the reserved crossing',()=>{const s=make({arenaCover:12}),props=s.features.filter(f=>f.battleFootprint),g=s.gridSize,b=s.battle,reserved=new Set(b.circulation);for(let i=0;i<props.length;i++){const f=props[i];for(const p of f.battleFootprint)assert(E.pointOnOrInside(p,b.arena.floor));for(let j=i+1;j<props.length;j++)assert(!E.polygonsIntersect(f.battleFootprint,props[j].battleFootprint));const xs=f.battleFootprint.map(p=>p[0]/g),ys=f.battleFootprint.map(p=>p[1]/g);for(let y=Math.floor(Math.min(...ys)+1e-6);y<Math.ceil(Math.max(...ys)-1e-6);y++)for(let x=Math.floor(Math.min(...xs)+1e-6);x<Math.ceil(Math.max(...xs)-1e-6);x++)assert(!reserved.has(y*b.cols+x));}});
test('HQ changes only appearance for all nineteen battle themes',()=>{for(const theme of Object.keys(B.PLANS)){const a=make({theme,hq:true}),b=make({theme,hq:false});assert.deepEqual(shape(a),shape(b),theme+' geometry changed');assert.deepEqual(C.vttData(a,100,'').line_of_sight,C.vttData(b,100,'').line_of_sight);const rich=R.render(a),plain=R.render(b);assert(rich.includes('data-hq="terrain"'));assert(rich.includes('data:image/png;base64,'));assert(!plain.includes('data-hq='));assert(!plain.includes('data:image/png;base64,'));assert(!/NaN|undefined|<script|https?:\/\/(?!www\.w3\.org)/.test(rich));}});
test('HQ flags survive save/load and explicit view overrides; old saves keep their look',()=>{for(const hq of [true,false]){const s=make({hq}),data=C.validateAtlas({format:'megamap-atlas',version:1,active:0,maps:[s]}),r=data.maps[0];assert.equal(r.appearance.hq,hq);assert.equal(r.options.hq,hq);assert.equal(R.render(r,{hq:!hq}).includes('data-hq="terrain"'),!hq);}const old=make();delete old.options.hq;delete old.appearance.hq;const before=JSON.stringify(old.features);C.validateAtlas({format:'megamap-atlas',version:1,active:0,maps:[old]});assert.equal(old.appearance.hq,false);assert.equal(JSON.stringify(old.features),before);assert(!R.render(old).includes('data-hq='));});
test('HQ is restricted to battle maps; importing rasters and player filtering stay safe',()=>{const s=E.generate('city','hq-city',{districts:12});assert.equal(C.appearance({...s,appearance:{hq:true}}).hq,false);const b=make();const prop=b.features.find(f=>f.battleProp);prop.hidden=true;assert(!R.render(b).includes('data-id="'+prop.id+'"'));prop.hidden=false;prop.gmOnly=true;assert(!R.render(b,{player:true}).includes('data-id="'+prop.id+'"'));});
test('Material PNGs have valid indexed pixels, palettes and deterministic seamless noise',()=>{for(const mat of ['grass','earth','sand','stone','wood','water','snow']){const a=M.texture(mat,'#789456');assert.equal(a,M.texture(mat,'#789456'));const png=Buffer.from(a.split(',')[1],'base64');assert.equal(png.subarray(1,4).toString(),'PNG');let bytes,pos=8;while(pos<png.length){const len=png.readUInt32BE(pos),type=png.subarray(pos+4,pos+8).toString();if(type==='IDAT')bytes=png.subarray(pos+8,pos+8+len);pos+=len+12;}const raw=zlib.inflateSync(bytes);assert.equal(raw.length,128*129);assert(new Set(raw).size>(['snow','water'].includes(mat)?40:80));}for(const x of [0,13.2,64,127.9])assert(Math.abs(M.noise(x,12,8,6)-M.noise(x+128,12,8,6))<1e-12);});
test('HQ shading remains deterministic, palette aware, and reflects edited floor cells',()=>{const s=make({theme:'castle'}),before=JSON.stringify(s);for(const palette of C.PALETTES){const a=R.render(s,{palette});assert.equal(a,R.render(s,{palette}));assert(!/NaN|undefined/.test(a));}assert.equal(JSON.stringify(s),before);const a=HQ.floorPath(s),i=s.battle.cells.indexOf(1);s.battle.cells[i]=0;assert.notEqual(HQ.floorPath(s),a);assert(R.render(s).includes('data-painted-solid="true"'));});
test('Arena metadata and arbitrary material inputs are safely bounded',()=>{for(const mutate of [s=>s.battle.arena.floor=[[NaN,0]],s=>s.battle.arena.tiers=Infinity,s=>s.features[1].arenaTier='<script>']){const s=make();mutate(s);assert.throws(()=>E.validateScene(s),/Invalid battle/);}const s=make();s.features.push({id:'malicious-material',type:'paint',points:[[0,0],[20,20]],width:8,paint:'x\")\"><script>alert(1)</script>'});E.validateScene(s);assert(!R.render(s).includes('<script>'));assert.equal(B.normalize({arenaTiers:999,arenaFloor:-20,arenaCover:NaN,hq:'false'}).hq,true);});
test('All new Arena/HQ UI copy has Italian translations',()=>{const window={};vm.runInNewContext(fs.readFileSync(require.resolve('../src/i18n.js'),'utf8'),{window});for(const text of ['Arena','Arena layout','Fighting floor','Spectator tiers','Arena obstacles','HQ · detailed materials and lighting','Arena entrance','Opposing entrance'])assert(window.MegamapI18n.isTranslated(text),text);});
