/* Part 2 acceptance: actual semantic coverage, usable compound geometry,
 * immutable old saves, bilingual display and bounded offline generation. */
'use strict';
const test=(name,fn)=>require('node:test')(name,async()=>{await new Promise(done=>setImmediate(done));return fn();}),assert=require('node:assert/strict'),fs=require('node:fs');
const E=require('../src/engine'),C=E.CITY_STUDIO,P=C.PLAN,S=P.Smart,R=require('../src/render'),V=require('../src/city-perspective'),Core=require('../src/editor-core'),A=require('../src/assets');
const clone=x=>JSON.parse(JSON.stringify(x));
const make=(extra={},seed='part2-check')=>E.generate('fantasy',seed,{preset:'river-capital',size:'city',boatCount:0,cityPlan:S.example(),...extra});
function checkGeometry(s){E.validateScene(s);const ix=new C.Index();for(const f of s.features.filter(f=>f.type==='building')){assert(C.dryPolygon(s.cityStudio.ground,f.polygon,0));if(s.cityStudio.paintPlan){const w=s.cityStudio.neighborhoods.find(w=>w.feature===f.ward);assert(P.fits(s,f.polygon,C,w),f.id+' escaped its assigned mask');}for(const a of ix.query(f.polygon))assert(!E.polygonsIntersect(f.polygon,a.poly),f.id+' overlaps '+a.value.id);ix.add(f.polygon,f);}
 const walls=s.features.filter(f=>f.type==='wall'&&f.cityComplex);for(const a of s.features.filter(f=>f.cityRole==='access'&&f.cityComplex)){const b=s.features.find(f=>f.id===a.cityBuilding);assert(b&&b.polygon);assert(E.nearPolyline(a.points.at(-1),[...b.polygon,b.polygon[0]])<.01,'access endpoint');for(let i=1;i<a.points.length;i++){const poly=C.corridor(a.points[i-1],a.points[i],a.width*.8);for(const hit of ix.query(poly))if(hit.value.id!==b.id)assert(!E.polygonsIntersect(poly,hit.poly),'approach crosses another building');for(const w of walls)for(let k=1;k<w.points.length;k++)assert(!E.polygonsIntersect(poly,C.corridor(w.points[k-1],w.points[k],w.width)),'fortress gate blocked');}}
 assert(s.features.every(f=>!f.notes));
}
test('Smart brush is appended without renumbering the sixteen shipped mask codes',()=>{for(const [i,id] of ['commons','slums','noble','oldtown','market','merchants','artisans','docks','temple','military','university','industrial','gardens','farming','cemetery','square'].entries())assert.equal(P.CODES[id],i+1);assert.equal(P.CODES.smart,17);});
test('Older painted example masks and geometry survive import without conversion',()=>{const a=JSON.parse(fs.readFileSync('examples/Painted-Cities.megamap.json')),before=JSON.stringify(a.maps.map(s=>s.features));Core.validateAtlas(a);assert.equal(JSON.stringify(a.maps.map(s=>s.features)),before);for(const s of a.maps)assert(s.cityStudio.paintPlan.zones.every(x=>x<=16));});
for(const seed of ['part2-check','smart-1','smart-2'])test('Smart capital '+seed+' fulfills every required quarter with physical content',()=>{const s=make({},seed),r=s.cityStudio.smartCity;assert.deepEqual(r.fulfilled,r.required);assert(!r.missing.length&&!r.unbuilt.length);assert(s.cityStudio.neighborhoods.some(w=>w.quarter==='slums'));assert(s.cityStudio.neighborhoods.some(w=>w.quarter==='noble'));const dock=s.cityStudio.neighborhoods.find(w=>w.quarter==='docks');assert(C.bankDistance(s.cityStudio.ground,dock.center)<=125);assert.equal(C.buildGraph(s).components.length,1);checkGeometry(s);});
test('Explicit quarter paint wins in hybrid plans and is not reassigned by the smart allocator',()=>{const p=S.example();p.strokes.push({role:'noble',width:120,points:[[230,245]]},{role:'square',width:65,points:[[430,450]]});const raw=P.compile(p),s=make({cityPlan:p}),st=s.cityStudio;for(let i=0;i<raw.zones.length;i++)if(raw.zones[i]&&raw.zones[i]!==P.CODES.smart)assert.equal(st.paintPlan.zones[i],raw.zones[i]);assert(st.neighborhoods.some(w=>!w.citySmart&&w.quarter==='noble'));checkGeometry(s);});
test('Smart zoning is deterministic and does not edit a stroke program',()=>{const p=S.example(),before=JSON.stringify(p),a=make({cityPlan:p}),b=make({cityPlan:p});assert.equal(JSON.stringify(a),JSON.stringify(b));assert.equal(JSON.stringify(p),before);});
test('An inland sketch reports a missing port instead of calling inland buildings docks',()=>{const p=S.example();p.strokes=p.strokes.filter(s=>s.role!=='river');const s=make({cityPlan:p});assert(s.cityStudio.smartCity.missing.includes('docks'));assert(!s.cityStudio.neighborhoods.some(w=>w.citySmart&&w.quarter==='docks'));assert(s.cityStudio.warnings.some(w=>w.includes('beside water')));});
test('Tiny and narrow plans disclose capacity constraints instead of inventing all city roles',()=>{const p={version:1,strokes:[{role:'smart',width:18,points:[[350,400],[550,400]]}]},s=make({cityPlan:p});assert(s.cityStudio.smartCity.missing.length||s.cityStudio.smartCity.unbuilt.length);checkGeometry(s);});
test('Unpainted ground and erased holes remain free of buildings in a smart plan',()=>{const p=S.example();p.strokes.push({role:'erase-districts',width:110,points:[[400,600]]});const s=make({cityPlan:p}),mask=P.compile(p);for(const f of s.features.filter(f=>f.type==='building'))assert(!P.touches(f.polygon,mask.zones,z=>z===0,C));checkGeometry(s);});
test('A tiny smart fishing settlement stays tiny, without a city fortress or great temple',()=>{const s=make({preset:'fishing',size:'hamlet',cityPlan:{version:1,strokes:[{role:'smart',width:280,points:[[300,300],[500,500]]},{role:'road',width:8,points:[[250,280],[530,530]]}]}});assert.deepEqual(s.cityStudio.smartCity.required,['commons']);assert(s.cityStudio.statistics.buildings<=4);assert(!s.features.some(f=>f.cityComplex));});
test('All ten presets have small, bounded and distinct mandatory-quarter programs',()=>{for(const p of C.PRESETS){const roles=S.program(C.resolve({preset:p.id}));assert(roles.length<=13);assert.equal(roles.length,new Set(roles).size);assert(roles.includes('commons'));}assert.notDeepEqual(S.program(C.resolve({preset:'river-capital'})),S.program(C.resolve({preset:'grove'})));});
for(const painted of [false,true])test((painted?'Painted':'Automatic')+' capital contains fitted fortress, temple, warehouse, park and monument complexes',()=>{const s=make({relief:0,...(painted?{}:{cityPlan:null})}),kinds=s.cityStudio.complexes.map(x=>x.kind);for(const k of ['fortress','temple','warehouse','park','square'])assert(kinds.includes(k),k+' absent');checkGeometry(s);const warehouses=s.features.filter(f=>f.cityComplexKind==='warehouse'&&f.type==='building');assert(warehouses.length>=2);assert(warehouses.every(f=>C.area(f.polygon)*s.scale*s.scale>300));const temple=s.features.find(f=>f.cityComplexKind==='temple'&&f.type==='building');const gardens=s.features.filter(f=>f.cityComplex===temple.cityComplex&&f.asset==='city-parterre');assert(gardens.length>=2);for(const f of gardens)assert(!E.polygonsIntersect(C.rect([f.x,f.y],f.size*2,f.size*2,f.rotation*Math.PI/180),temple.polygon));});
test('Reserved compounds remain clear of ordinary buildings and survive district regeneration',()=>{const s=make({relief:0}),complex=s.cityStudio.complexes.find(c=>c.kind==='fortress'),parts=s.features.filter(f=>f.cityComplex===complex.id).map(clone),ground=s.features.find(f=>f.id===complex.id);for(const f of s.features.filter(f=>f.type==='building'&&!f.cityComplex))assert(!E.polygonsIntersect(f.polygon,ground.polygon));E.regenerateDistrict(s,complex.ward,'commons');for(const f of parts)assert.deepEqual(s.features.find(x=>x.id===f.id),f);E.validateScene(s);});
test('New city ornaments are original, bundled SVGs with Italian names',()=>{const CA=require('../src/city-assets');assert.equal(A.catalog.length,304);for(const id of ['city-guard-post','city-temple-steps','city-parterre','city-statue-plinth','city-grand-fountain','city-dock-crane','city-warehouse-cargo','city-park-pavilion','city-market-arcade','city-granary-silos']){assert(A.byId[id]);assert(CA.IT[A.byId[id].name]);assert.equal(fs.readFileSync('assets/svg/'+id+'.svg','utf8'),R.assetFile(id));}assert.equal(new Set(CA.assets.map(a=>a.body)).size,26);});
test('New complexes render in Italian and English, top-down and 2.5D, without mutating geometry',()=>{const s=make({relief:0}),before=JSON.stringify(s);for(const language of ['it','en'])for(const hq of [true,false]){const a=R.render(s,{language,hq}),b=V.render(s,{language,hq});for(const text of language==='it'?['Grande tempio','Fortezza interna']:['Great temple','Inner fortress'])assert(a.includes(text)&&b.includes(text),text);assert(!/NaN|undefined|<script/.test(a+b));}assert.equal(JSON.stringify(s),before);});
test('New report and complex metadata reject corrupt imports',()=>{const good=make();for(const edit of [s=>s.cityStudio.smartCity.version=99,s=>s.cityStudio.smartCity.required=['<script>'],s=>s.cityStudio.complexes[0].sizeFactor=Infinity,s=>s.features.find(f=>f.cityComplex).cityComplex={}]){const s=clone(good);edit(s);assert.throws(()=>E.validateScene(s));}});
test('Smart brush remains wizard-only with a collapsed optional detailed palette',()=>{const code=fs.readFileSync('src/city-paint.js','utf8');assert(code.includes("selected='smart'"));assert(code.includes('cityPaintDetailed'));assert(!fs.readFileSync('src/city-ui.js','utf8').includes('cityPaint'));assert(fs.readFileSync('src/app.js','utf8').includes('delete opts.cityPlan'));});

test('A gate touching a rotated lot boundary is accepted without an interior crossing',()=>{const plan=S.example();plan.strokes.push({role:'smart',width:140,points:[[190,330],[230,450]]});const s=make({cityPlan:plan,relief:0},'part2-browser');assert(s.cityStudio.complexes.some(c=>c.kind==='fortress'));checkGeometry(s);});

test('Every preset fulfills its size-appropriate smart program on a broad connected sketch',()=>{for(const preset of C.PRESETS){const s=make({preset:preset.id,size:'recommended'},'part2-matrix');E.validateScene(s);assert.deepEqual(s.cityStudio.smartCity.fulfilled,s.cityStudio.smartCity.required,preset.id);}});
