'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/engine.js'),R=require('../src/render.js');
function connected(s){const {cols,rows,cells}=s.battle,start=cells.indexOf(1);assert(start>=0);const seen=new Set([start]),q=[start];for(let k=0;k<q.length;k++){const i=q[k],x=i%cols,y=Math.floor(i/cols);for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,yy=y+dy,n=yy*cols+xx;if(xx<0||yy<0||xx>=cols||yy>=rows||!cells[n]||seen.has(n))continue;seen.add(n);q.push(n);}}return seen.size===cells.filter(Boolean).length;}
for(const mode of['region','city','battle']){
 test(mode+': deterministic scene and SVG',()=>{const a=E.generate(mode,'repeatable',{}),b=E.generate(mode,'repeatable',{});assert.deepEqual(a,b);assert.equal(R.render(a),R.render(b));});
 test(mode+': seed variation',()=>assert.notDeepEqual(E.generate(mode,'alpha',{}),E.generate(mode,'beta',{})));
 test(mode+': JSON roundtrip',()=>{const s=E.generate(mode,'roundtrip',{});assert.deepEqual(E.validateScene(JSON.parse(JSON.stringify(s))),s);});
 test(mode+': 12 seed stress test',()=>{for(let k=0;k<12;k++){const s=E.generate(mode,'stress-'+k,{});E.validateScene(s);assert(s.features.length<40000);assert(new Set(s.features.map(f=>f.id)).size===s.features.length);for(const f of s.features){if(f.polygon){assert(f.polygon.length>=3);assert(E.area(f.polygon)>0);}}assert(!R.render(s).includes('NaN'));}});
}
test('Watabou-derived subdivision preserves area bounds',()=>{const p=[[0,0],[100,0],[100,100],[0,100]];for(let k=0;k<20;k++){const lots=E.createAlleys(p,70,.6,.5,E.rng(k));assert(lots.length>20);assert(lots.reduce((a,p)=>a+E.area(p),0)<=10000.01);assert(lots.every(p=>E.area(p)>0));}});
test('Subdivision handles degenerate input',()=>{assert.deepEqual(E.createAlleys([],100,.4,.4,E.rng(1)),[]);assert.deepEqual(E.createAlleys([[0,0],[1,0],[2,0]],100,.4,.4,E.rng(1)),[]);});
test('Convex clipping and inset',()=>{const p=[[0,0],[100,0],[100,100],[0,100]];assert.equal(E.area(E.clip(p,[1,0],50)),5000);assert.equal(E.area(E.inset(p,10)),6400);assert.deepEqual(E.inset(p,80),[]);});
test('Voronoi covers the original bounding box',()=>{const p=[[0,0],[100,0],[100,100],[0,100]],cells=E.voronoi([[20,20],[80,20],[50,75]],p);assert(Math.abs(cells.reduce((n,p)=>n+E.area(p),0)-10000)<1e-6);});
test('Default region is 20 km square',()=>{const s=E.generate('region','20km',{});assert.equal(s.scale,20);assert.equal(s.units,'km');assert.equal(s.width,s.height);});
test('Every regional landform remains valid',()=>{for(const terrain of['valley','island','coast','highlands','archipelago'])for(const water of[.1,.36,.7])E.validateScene(E.generate('region','landforms',{terrain,water}));});
test('Region road endpoints meet generated settlements',()=>{const s=E.generate('region','roads',{}),towns=s.features.filter(f=>f.type==='settlement');for(const f of s.features.filter(f=>f.type==='road')){assert(towns.some(t=>E.dist(f.points[0],[t.x,t.y])<.01));assert(towns.some(t=>E.dist(f.points.at(-1),[t.x,t.y])<.01));}});
test('Region naming does not duplicate settlements',()=>{const s=E.generate('region','names',{settlements:30});const a=s.features.filter(f=>f.type==='settlement').map(f=>f.label);assert.equal(new Set(a).size,a.length);});
test('City options toggle water and walls',()=>{const s=E.generate('city','dry',{river:false,walls:false});assert(!s.features.some(f=>f.type==='river'||f.type==='wall'));});
test('City density affects building count',()=>{const a=E.generate('city','density',{density:.2}),b=E.generate('city','density',{density:1});assert(b.features.filter(f=>f.type==='building').length>a.features.filter(f=>f.type==='building').length);});
test('City river avoids building centers',()=>{const s=E.generate('city','river-city',{}),river=s.features.find(f=>f.type==='river');for(const b of s.features.filter(f=>f.type==='building'))assert(E.nearPolyline([b.x,b.y],river.points)>=25);});
for(const theme of['dungeon','cave','forest','ruins'])test(theme+': connected floor for 15 seeds',()=>{for(let k=0;k<15;k++){const s=E.generate('battle','connect-'+k,{theme,cols:32,rows:24});assert(connected(s),theme+' disconnected for '+k);E.validateScene(s);}});
test('Battle map dimensions and wall bounds',()=>{const s=E.generate('battle','walls',{cols:50,rows:30});assert.equal(s.height,600);assert.equal(s.gridSize,20);assert.equal(s.scale,250);assert(E.wallSegments(s).length>0);for(const line of E.wallSegments(s))for(const p of line){assert(p[0]>=0&&p[0]<=1000);assert(p[1]>=0&&p[1]<=600);}});
test('Forest VTT has no implicit room walls',()=>assert.equal(E.wallSegments(E.generate('battle','forest',{theme:'forest'})).length,0));
test('All 278 built-in assets can be rendered independently',()=>{assert.equal(E.ASSETS.length,278);for(const asset of E.ASSETS){const svg=R.assetFile(asset);assert(svg.startsWith('<svg'));assert(svg.includes('id="preview-'+asset+'-'+asset+'"'));assert(!svg.includes('undefined'));}});
test('Text export escapes markup',()=>{const s=E.generate('battle','escape',{});s.title='"><script>alert(1)</script>';s.features.push({id:'evil',type:'label',x:10,y:10,label:'<img onerror="oops">'});const svg=R.render(s);assert(!svg.includes('<script>'));assert(!svg.includes('<img '));assert(svg.includes('&lt;script&gt;'));});
test('Import rejects invalid dimensions and formats',()=>{assert.throws(()=>E.validateScene({}));const s=E.generate('battle','validate',{});s.width=NaN;assert.throws(()=>E.validateScene(s));});
test('Import rejects active SVG image payloads',()=>{const s=E.generate('battle','validate',{});s.features.push({id:'evil',type:'image',x:20,y:20,size:10,data:'data:image/svg+xml,<svg onload="alert(1)"/>'});assert.throws(()=>E.validateScene(s));});
test('Import rejects duplicate feature IDs',()=>{const s=E.generate('city','validate',{});s.features.push(s.features[0]);assert.throws(()=>E.validateScene(s));});
test('Out-of-range generation inputs are bounded',()=>{const s=E.generate('city','bounds',{districts:1,density:99,sizeKm:-1});assert.equal(s.options.districts,12);assert.equal(s.options.density,1);assert.equal(s.scale,.5);});
test('Every palette and grid produces finite SVG',()=>{for(const mode of['region','city','battle']){const s=E.generate(mode,'styles',{});for(const palette of Object.keys(R.palettes))for(const grid of['none','square','hex']){const out=R.render(s,{palette,grid});assert(out.startsWith('<svg'));assert(out.endsWith('</svg>'));assert(!out.includes('NaN'));}}});
