'use strict';
const test=require('node:test'), assert=require('node:assert/strict'), fs=require('node:fs'),path=require('node:path');
const E=require('../src/engine.js'),C=require('../src/editor-core.js'),R=require('../src/render.js'),A=require('../src/assets.js');
const copy=C.clone,battle=(seed='v1',options={})=>E.generate('battle',seed,options);
function connected(s){const{cols,rows,cells}=s.battle,root=cells.indexOf(1);assert(root>=0);const seen=new Set([root]),q=[root];for(let k=0;k<q.length;k++){const i=q[k],x=i%cols,y=Math.floor(i/cols);for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const a=x+dx,b=y+dy,j=b*cols+a;if(a>=0&&a<cols&&b>=0&&b<rows&&cells[j]&&!seen.has(j)){seen.add(j);q.push(j);}}}return seen.size===cells.filter(Boolean).length;}
function feature(s,f){s.features.push({id:'test-'+s.features.length,...f});return s;}
function atlas(s=battle()){return{format:'megamap-atlas',version:1,active:0,maps:[s],library:[]};}
test('Version is 1.2.0',()=>assert.equal(E.VERSION,'1.2.0'));
test('Catalog has 278 unique IDs and fourteen categories',()=>{assert.equal(A.catalog.length,278);assert.equal(new Set(A.catalog.map(x=>x.id)).size,278);assert.equal(A.categories.length,14);assert.deepEqual(E.ASSETS,A.catalog.map(x=>x.id));});
test('New drawings are distinct, resolved and self-contained',()=>{const bodies=A.catalog.filter(a=>a.body).map(a=>a.body);assert.equal(bodies.length,238);assert.equal(new Set(bodies).size,238);for(const id of E.ASSETS){const svg=R.assetFile(id);assert(!/@(?:paper|roof|water|ink|forest|tree)/.test(svg));assert(!/NaN|undefined|<script|<image/.test(svg));assert(!/href="https?:/.test(svg));}});
test('All six palettes render every asset',()=>{for(const palette of C.PALETTES)for(const id of E.ASSETS){const s=R.assetPreview(id,palette,52);assert(s.includes('<svg'));assert(!s.includes('undefined'));}});
for(const layout of ['organic','planned','radial']){
 test(layout+': city generation is repeatable',()=>{const a=E.generate('city','layout-'+layout,{layout}),b=E.generate('city','layout-'+layout,{layout});assert.deepEqual(a,b);assert.equal(a.options.layout,layout);});
 test(layout+': ward links and IDs survive filtering',()=>{for(let seed=0;seed<8;seed++){const s=E.generate('city','links-'+seed,{layout,river:!!(seed%2),walls:true,districts:55});E.validateScene(s);const wards=new Set(s.features.filter(f=>f.type==='district').map(f=>f.id));assert.equal(s.features.length,new Set(s.features.map(f=>f.id)).size);for(const b of s.features.filter(f=>f.type==='building'))assert(wards.has(b.ward));}});
}
test('City layout preferences change actual geometry',()=>{const a=E.generate('city','same-seed',{layout:'organic'});for(const layout of ['planned','radial'])assert.notDeepEqual(a.features,E.generate('city','same-seed',{layout}).features);});
for(const theme of ['dungeon','forest','cave','ruins','tavern','temple','sewer','bridge','desert','ice-cave']){
 test(theme+': connected floor at 16, 32 and 80 columns',()=>{for(const cols of [16,32,80]){const s=battle('theme-'+cols,{theme,cols,rows:24});E.validateScene(s);assert(connected(s),theme+' '+cols);assert(!R.render(s).includes('NaN'));}});
}
test('Open terrain themes have no implicit LOS walls',()=>{for(const theme of ['forest','desert','bridge'])assert.equal(E.wallSegments(battle('open',{theme})).length,0);});
test('Regional extent 2, 20, 100 km and contours remain finite',()=>{for(const sizeKm of [2,20,100]){const s=E.generate('region','region-size',{sizeKm});assert.equal(s.scale,sizeKm);E.validateScene(s);assert(!/NaN|undefined/.test(R.render(s,{contours:true})));}});
test('Per-map appearance is sanitized and survives atlas roundtrip',()=>{const a=atlas();a.maps[0].appearance={palette:'frost',grid:'hex',contours:true,textures:false,layers:{labels:false,water:false}};const loaded=C.validateAtlas(copy(a));assert.equal(loaded.maps[0].appearance.palette,'frost');assert.equal(loaded.maps[0].appearance.layers.water,false);assert.equal(loaded.maps[0].appearance.layers.assets,true);assert.equal(loaded.maps[0].appearance.textures,false);assert.equal(C.appearance({...a.maps[0],appearance:{palette:'evil',grid:'huge'}}).palette,'atlas');});
test('Standalone scene becomes a one-map atlas',()=>assert.equal(C.validateAtlas(battle()).maps.length,1));
test('Atlas rejects zero maps, too many maps and unknown versions',()=>{for(const maps of [[],Array(31).fill(battle())])assert.throws(()=>C.validateAtlas({format:'megamap-atlas',version:1,maps}));assert.throws(()=>C.validateAtlas({...atlas(),version:99}));});
test('Atlas validates imported raster library and rejects remote/active URLs',()=>{const a=atlas();a.library=[{id:'custom-1',name:'Original image',data:'data:image/png;base64,AAAA',aspect:2}];assert.equal(C.validateAtlas(a).library.length,1);for(const data of ['http://example.invalid/a.png','data:image/svg+xml;base64,AAAA','data:text/html;base64,AAAA']){const bad=copy(a);bad.library[0].data=data;assert.throws(()=>C.validateAtlas(bad));}});
test('Atlas rejects duplicate library IDs and malformed aspects',()=>{const a=atlas();a.library=[{id:'a',name:'A',data:'data:image/png;base64,AAAA',aspect:1}];a.library.push(copy(a.library[0]));assert.throws(()=>C.validateAtlas(a));a.library.pop();a.library[0].aspect=NaN;assert.throws(()=>C.validateAtlas(a));});
for(const [name,f] of Object.entries({path:{type:'road',width:2},polygon:{type:'area',polygon:[[0,0],[1,1]]},point:{type:'asset',asset:'tree'},portal:{type:'portal',points:[[1,1],[2,2],[3,3]]},width:{type:'road',points:[[0,0],[10,10]],width:-2},coordinate:{type:'label',x:NaN,y:5}}))test('Invalid '+name+' geometry is rejected',()=>assert.throws(()=>E.validateScene(feature(battle(),f))));
test('Non-finite roof/z geometry is rejected',()=>{for(const key of ['roof','z'])assert.throws(()=>E.validateScene(feature(battle(),{type:'label',x:10,y:10,[key]:Infinity})));});
test('Battle grid dimensions must agree with rendered geometry',()=>{const s=battle();s.height+=1;assert.throws(()=>E.validateScene(s));});
test('A region must retain its heightmap',()=>{const s=E.generate('region','missing',{});delete s.terrain;assert.throws(()=>E.validateScene(s));});
test('Unknown asset falls back to a bundled rock',()=>{const s=feature(battle(),{type:'asset',x:10,y:10,size:20,asset:'unknown'});E.validateScene(s);assert.equal(s.features.at(-1).asset,'rock');});
test('Invalid light colors are normalized',()=>{const s=feature(battle(),{type:'light',x:10,y:10,color:'url(evil)',range:200,intensity:10});E.validateScene(s);assert.equal(s.features.at(-1).range,100);assert.equal(s.features.at(-1).intensity,5);assert.equal(s.features.at(-1).color,'#ffc477');});
test('Contour extraction handles an entirely empty grid',()=>assert.deepEqual(C.contours(Array(64).fill(0),8,.5),[]));
test('Contour extraction closes a full-grid boundary',()=>{const lines=C.contours(Array(64).fill(1),8,.5);assert.equal(lines.length,1);assert.deepEqual(lines[0][0],lines[0].at(-1));assert(E.area(lines[0])>100000);});
test('Contour extraction preserves a lake-sized hole',()=>{const a=Array(64).fill(1);for(let y=2;y<6;y++)for(let x=2;x<6;x++)a[y*8+x]=0;const loops=C.contours(a,8,.5);assert.equal(loops.length,2);for(const p of loops)assert.deepEqual(p[0],p.at(-1));});
test('Saddle contours have finite coordinates and closed paths',()=>{for(const values of [[1,0,0,1],[0,1,1,0]])for(const p of C.contours(values,2,.5)) {assert.deepEqual(p[0],p.at(-1));assert(p.flat().every(Number.isFinite));}});
test('Translation moves point, line and polygon geometry',()=>{const f={x:5,y:8,polygon:[[0,0],[10,0],[10,10]],points:[[1,1],[2,2]]};C.translate(f,4,-2);assert.equal(f.x,9);assert.deepEqual(f.polygon[0],[4,-2]);assert.deepEqual(f.points[0],[5,-1]);});
test('Rotation preserves polygon area',()=>{const f={polygon:[[0,0],[10,0],[10,5],[0,5]]};C.rotate(f,37);assert(Math.abs(E.area(f.polygon)-50)<1e-7);});
test('Scaling geometry multiplies area and symbol size',()=>{const f={polygon:[[0,0],[10,0],[10,10],[0,10]],size:10};C.scale(f,2);assert.equal(E.area(f.polygon),400);assert.equal(f.size,20);});
test('Path smoothing retains exact endpoints',()=>{const points=[[0,0],[20,40],[80,10],[100,50]],s=C.smooth(points);assert.deepEqual(s[0],points[0]);assert.deepEqual(s.at(-1),points.at(-1));assert(s.length>points.length);});
test('Scatter rejects outside and occupied floor cells',()=>{const s=battle('scatter',{theme:'dungeon'});assert.equal(C.canPlace(s,[-1,5]),false);const n=s.battle.cells.indexOf(0);assert.equal(C.canPlace(s,[(n%s.battle.cols+.5)*s.gridSize,(Math.floor(n/s.battle.cols)+.5)*s.gridSize]),false);});
test('Wall merging joins only collinear adjacent intervals',()=>{const lines=C.mergeWalls([[[0,0],[10,0]],[[10,0],[20,0]],[[30,0],[40,0]],[[5,0],[5,10]],[[5,10],[5,20]],[[0,1],[10,2]]]);assert.equal(lines.length,4);assert(lines.some(l=>JSON.stringify(l)==='[[0,0],[20,0]]'));});
test('Door subtraction preserves both remaining wall sections',()=>assert.deepEqual(C.cutDoor([[0,0],[100,0]],[[40,0],[60,0]]),[[[0,0],[40,0]],[[60,0],[100,0]]]));
test('Offset and external doors do not erase walls',()=>{for(const door of [[[40,30],[60,30]],[[110,0],[150,0]],[[100,0],[100,10]]])assert.deepEqual(C.cutDoor([[0,0],[100,0]],door),[[[0,0],[100,0]]]);});
test('Reversed doors cut the same opening',()=>assert.deepEqual(C.cutDoor([[0,0],[100,0]],[[60,0],[40,0]]),C.cutDoor([[0,0],[100,0]],[[40,0],[60,0]])));
test('UVTT exports wall openings, portals and independent light metadata',()=>{const s=battle('uvtt',{theme:'forest',cols:20,rows:20});s.features=[];feature(s,{type:'wall',points:[[100,100],[300,100]],width:4});feature(s,{type:'portal',points:[[150,100],[200,100]]});feature(s,{type:'light',x:250,y:200,range:8,intensity:1.5,color:'#ffbb55'});const v=C.vttData(s,100,'AAAA');assert.equal(v.format,.2);assert.equal(v.resolution.pixels_per_grid,100);assert.equal(v.line_of_sight.length,2);assert.equal(v.portals.length,1);assert.equal(v.portals[0].closed,true);assert.equal(v.lights[0].range,8);assert.equal(v.lights[0].color,'ffffbb55');assert.equal(v.lights[0].position.x,5);assert.equal(v.image,'AAAA');});
test('Player UVTT omits hidden and GM-only walls, portals and lights',()=>{const s=battle('uvtt-hidden',{theme:'forest'});s.features=[];feature(s,{type:'wall',points:[[10,10],[20,10]],width:2,gmOnly:true});feature(s,{type:'portal',points:[[10,10],[20,10]],gmOnly:true});feature(s,{type:'light',x:50,y:50,hidden:true});const player=C.vttData(s,100,'',true),gm=C.vttData(s,100,'',false);assert.equal(player.line_of_sight.length,0);assert.equal(player.portals.length,0);assert.equal(player.lights.length,0);assert.equal(gm.portals.length,1);});
test('UVTT rejects regional maps',()=>assert.throws(()=>C.vttData(E.generate('region','vtt',{}),100,'')));
test('Player SVG omits GM-only labels and hidden labels',()=>{const s=battle();feature(s,{type:'label',x:10,y:10,label:'HIDDEN_SECRET_TOKEN',hidden:true});feature(s,{type:'label',x:20,y:20,label:'GM_SECRET_TOKEN',gmOnly:true});assert(!R.render(s,{player:true}).includes('GM_SECRET_TOKEN'));assert(!R.render(s,{player:false}).includes('HIDDEN_SECRET_TOKEN'));assert(R.render(s,{player:false}).includes('GM_SECRET_TOKEN'));});
test('Portal labels and editor lights render without NaN',()=>{const s=battle();feature(s,{type:'portal',points:[[10,10],[20,10]],label:'Door'});feature(s,{type:'light',x:10,y:10,range:5,color:'#ffbb22'});const svg=R.render(s,{editor:true});assert(!/NaN|undefined/.test(svg));});
test('History undo/redo follows edits and clears redo on branching',()=>{const h=C.history();h.push('a');assert.equal(h.undo('b'),'a');assert.equal(h.redo('a'),'b');h.undo('b');h.push('a2');assert.equal(h.canRedo,false);assert.equal(h.undo('c'),'a2');});
test('History respects entry limit',()=>{const h=C.history(2);h.push('a');h.push('b');h.push('c');assert.equal(h.undo('d'),'c');assert.equal(h.undo('c'),'b');assert.equal(h.undo('b'),null);});
test('History respects memory budget while preserving one undo',()=>{const h=C.history(40,10);h.push('aaaaaa');h.push('bbbbbb');assert.equal(h.undo('c'),'bbbbbb');assert.equal(h.undo('b'),null);});
test('Imported old city ward references are repaired by containment',()=>{const s=E.generate('city','legacy',{});s.engineVersion='0.1.0';const b=s.features.find(f=>f.type==='building');b.ward='bad-legacy-id';C.validateAtlas(s);const d=s.features.find(d=>d.type==='district'&&d.id===b.ward);assert(d);assert(E.inside(C.center(b),d.polygon));assert.equal(s.metadata.wardLinksMigrated,true);});
test('HTML references all local runtime files and uses no network sources',()=>{const dir=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(dir,'index.html'),'utf8');for(const m of html.matchAll(/(?:src|href)="([^"#]+)"/g)){if(m[1].startsWith('data:'))continue;assert(!/^https?:/.test(m[1]));assert(fs.existsSync(path.join(dir,m[1])),'Missing '+m[1]);}});
test('The actual supplied v0.1 city file opens under the v1 validator',()=>{const old=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/v0.1-city.megamap.json'),'utf8'));const loaded=C.validateAtlas(old);assert.equal(loaded.maps.length,1);assert.equal(loaded.maps[0].mode,'city');assert(loaded.maps[0].features.some(f=>f.type==='building'));});
test('Every shipped example atlas validates with distinct map IDs',()=>{for(const file of ['Starter-atlas.megamap.json','Ten-encounters.megamap.json']){const a=C.validateAtlas(JSON.parse(fs.readFileSync(path.join(__dirname,'../examples',file),'utf8')));assert.equal(new Set(a.maps.map(m=>m.documentId)).size,a.maps.length);}});
