from pathlib import Path
p=Path('src/city-complexes.js');s=p.read_text()
s=s.replace("  const ordered=wards.sort((a,b)=>spec.quarters.indexOf(a.quarter)-spec.quarters.indexOf(b.quarter));let placed=false;", "  st.reservations=st.reservations.filter(r=>!wards.some(w=>r.smartSite===w.id&&w.smartSite?.kind===spec.kind));\n  const ordered=wards.sort((a,b)=>spec.quarters.indexOf(a.quarter)-spec.quarters.indexOf(b.quarter));let placed=false;")
s=s.replace("    for(const slot of samples.slice(0,100).concat(samples.filter(x=>x.route),interior.slice(0,120))){const cs=Math.cos(slot.angle),sn=Math.sin(slot.angle),T=(x,y)=>[slot.center[0]+cs*x-sn*y*slot.side,slot.center[1]+sn*x+cs*y*slot.side],box=(x,y,w,h)=>[T(x-w/2,y-h/2),T(x+w/2,y-h/2),T(x+w/2,y+h/2),T(x-w/2,y+h/2)],poly=box(0,0,W,D);", "    const pinned=[];if(ward.smartSite?.kind===spec.kind&&ward.smartSite.factor===factor){const center=ward.center.slice(),angle=ward.smartSite.angle;for(const side of [-1,1]){const gate=[center[0]+Math.sin(angle)*D/2*side,center[1]-Math.cos(angle)*D/2*side],near=C.nearestRoad(s,gate);if(near)pinned.push({center,angle,side,near,route:true});}}\n    for(const slot of pinned.concat(samples.slice(0,100),samples.filter(x=>x.route),interior.slice(0,120))){const cs=Math.cos(slot.angle),sn=Math.sin(slot.angle),T=(x,y)=>[slot.center[0]+cs*x-sn*y*slot.side,slot.center[1]+sn*x+cs*y*slot.side],box=(x,y,w,h)=>[T(x-w/2,y-h/2),T(x+w/2,y-h/2),T(x+w/2,y+h/2),T(x-w/2,y+h/2)],poly=box(0,0,W,D);")
s=s.replace(" }\nfunction harbors(s,C)", " st.reservations=st.reservations.filter(r=>!r.smartSite);for(const w of st.neighborhoods)delete w.smartSite;\n}\nfunction harbors(s,C)")
p.write_text(s)

p=Path('src/map-labels.js');s=p.read_text()
s=s.replace("const IT=Object.freeze({", "const IT=Object.freeze({\n \"Some vessels do not fit the painted channels. Widen the river or choose a smaller fleet type.\": \"Alcune imbarcazioni non entrano nei canali dipinti. Allarga il fiume o scegli una flotta di barche più piccole.\",",1)
s=s.replace(" if((m=value.match(/^City complex could not fit safely:", " if((m=value.match(/^Painted building land: ([\\d.]+) ha before streets and courtyards\\. Increase settlement size or lower the building target; unpainted land stays open\\.$/)))return `Terreno edificabile dipinto: ${m[1].replace('.',',')} ha prima di strade e cortili. Aumenta la dimensione dell’insediamento o riduci il numero di edifici richiesti; il terreno non dipinto resta libero.`;\n if((m=value.match(/^City complex could not fit safely:")
p.write_text(s)
