/* Developer utility: regenerates the distributable SVG library. No packages required. */
const fs=require('node:fs'),path=require('node:path'),A=require('../src/assets.js'),R=require('../src/render.js');
const root=path.resolve(__dirname,'../assets');fs.mkdirSync(path.join(root,'svg'),{recursive:true});
for(const a of A.catalog)fs.writeFileSync(path.join(root,'svg',a.id+'.svg'),R.assetFile(a.id));
fs.writeFileSync(path.join(root,'catalog.json'),JSON.stringify({version:'1.2.0',license:'GPL-3.0-only',count:A.catalog.length,categories:A.categories,assets:A.catalog.map(({body,...a})=>({...a,file:'svg/'+a.id+'.svg'}))},null,2));
const esc=R.esc;
const body=A.categories.map(cat=>`<section><h2>${esc(cat)}</h2><div class="grid">${A.catalog.filter(a=>a.category===cat).map(a=>`<a class="card" data-key="${esc((a.id+' '+a.name+' '+cat+' '+(a.tags||'')).toLowerCase())}" href="svg/${a.id}.svg" target="_blank" rel="noopener"><img src="svg/${a.id}.svg" width="112" height="112" alt="${esc(a.name)}" loading="lazy"><strong>${esc(a.name)}</strong><small>${esc(a.id)}</small></a>`).join('')}</div></section>`).join('');
fs.writeFileSync(path.join(root,'catalog.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Megamap — ${A.catalog.length} asset catalog</title><style>body{margin:0;background:#f1eee2;color:#30433b;font:15px/1.6 system-ui,sans-serif}header,main{max-width:1100px;margin:auto;padding:32px}header{padding-top:60px}nav{font-size:13px;display:flex;gap:25px}a{color:inherit}h1{font-size:52px;font-weight:550;letter-spacing:-2px;line-height:1.1}h2{font-weight:550;margin-top:44px}p{max-width:760px;color:#58675e}.eyebrow{font-size:12px;letter-spacing:2px}input{box-sizing:border-box;width:100%;padding:15px;background:#fffdf3;color:#30433b;border:1px solid #c7cfbf;border-radius:8px;font:inherit;margin-top:18px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(135px,1fr));gap:12px}.card{display:flex;flex-direction:column;align-items:center;text-align:center;background:#faf8ed;border:1px solid #d0d5c8;padding:12px;border-radius:8px;text-decoration:none;transition:background .15s}.card:hover{background:#e6eddf}.card strong{font-weight:550;font-size:13px;margin-top:6px}.card small{font-size:11px;color:#6d7d70}.card[hidden],section[hidden]{display:none}footer{padding:30px 0;font-size:12px;color:#637361}img{object-fit:contain;max-width:100%}</style><header><nav><a href="../index.html">Open Megamap</a><a href="../README.html">Scope & target</a><a href="../docs/guide.html">User guide</a></nav><p class="eyebrow">MEGAMAP 1.2 / ORIGINAL VECTOR LIBRARY</p><h1>${A.catalog.length} symbols.<br>${A.categories.length} collections.</h1><p>The 246-symbol v1.2 library plus 32 battle-landscape/manor props and 16 distinct City details. These are stylized cartographic symbols and top-down props, not photorealistic battlemaps. In the workbench they adapt to your chosen palette. The files below use the Field Atlas palette and have transparent backgrounds.</p><p>Click a card to open its standalone SVG. Use Footprints for top-down buildings; Buildings are pictorial town and regional landmarks. Symbols are included under GPL-3.0-only. See the project LICENSE and NOTICE.</p><input id="search" aria-label="Search catalog" placeholder="Search by name, category, or tag…"><p id="count">${A.catalog.length} assets</p></header><main>${body}<footer>No external images, web fonts or network requests. Asset definitions: src/assets.js, src/city-assets.js, src/encounter-content.js and src/render.js.</footer></main><script>document.getElementById('search').oninput=function(){const q=this.value.toLowerCase().trim();let count=0;for(const card of document.querySelectorAll('.card')){card.hidden=!card.dataset.key.includes(q);if(!card.hidden)count++;}for(const section of document.querySelectorAll('section'))section.hidden=!section.querySelector('.card:not([hidden])');document.getElementById('count').textContent=count+' of ${A.catalog.length} assets';};</script></html>`);
console.log(`Wrote ${A.catalog.length} SVG assets and catalog.`);
