/* Compact City Studio controls shared by sidebar and the existing wizard. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else{root.MegamapCityUI=api;root.MegamapI18n?.register(api.IT);}})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const IT={
 'Housing climate':'Clima delle abitazioni','Climate by architecture':'Clima secondo l’architettura','Temperate':'Temperato','Hot and dry':'Caldo e secco','Hot and humid':'Caldo e umido','Cold / snowy':'Freddo / nevoso',
 'City Studio':'Studio città','City · legacy':'Città · classica','Fantasy settlements':'Insediamenti fantasy','Settlement':'Insediamento','Customize':'Personalizza','Settlement size':'Dimensione dell’insediamento','By preset':'Secondo il modello','Hamlet · a few huts':'Borgata · poche capanne','Village':'Villaggio','Town':'Borgo','City':'Città','Capital':'Capitale','Urban fabric':'Tessuto urbano','Organic growth':'Crescita organica','Old lanes & planned precincts':'Vicoli antichi e quartieri pianificati','Planned precincts':'Quartieri pianificati','Visual detail':'Dettaglio visivo','Quiet':'Sobrio','Balanced':'Equilibrato','Rich':'Ricco','Landscape setting':'Contesto geografico','Open plain':'Pianura aperta','Great river':'Grande fiume','Seacoast':'Costa marina','Fjord & slopes':'Fiordo e pendii','Hills & terraces':'Colline e terrazze','Lagoon & canals':'Laguna e canali','Woodland':'Bosco','Oasis basin':'Bacino dell’oasi','Architectural character':'Carattere architettonico','Vernacular':'Tradizionale','Imperial':'Imperiale','Nordic timber':'Legno nordico','Mountain stone':'Pietra montana','Merchant courts':'Corti mercantili','Woodland halls':'Sale del bosco','Desert courts':'Corti del deserto','Arcane stone':'Pietra arcana','Fantasy landmark':'Monumento fantasy','No extraordinary landmark':'Nessun monumento straordinario','Great tree':'Grande albero','Impact crater':'Cratere d’impatto','Fallen colossus':'Colosso caduto','Crystal spires':'Guglie di cristallo','Visible history':'Storia visibile','New settlement':'Insediamento nuovo','Old quarter':'Quartiere antico','Successive growth':'Crescita stratificata','Ancient remains':'Resti antichi','Defenses':'Difese','No walls':'Senza mura','City enclosure':'Cinta cittadina','High citadel':'Cittadella alta','Growth boundary':'Limite di crescita','Terrain-led':'Secondo il terreno','Strict oval':'Ovale vincolante','Strict rectangle':'Rettangolo vincolante','Strict elongated form':'Forma allungata vincolante','Waterfront fleet':'Flotta sul lungomare','No boats':'Senza imbarcazioni','Fishing skiffs':'Barche da pesca','Trading vessels':'Navi mercantili','Naval armada':'Armata navale','Longships':'Drakkar','Optional city layers':'Livelli città facoltativi','Rooftop connections':'Collegamenti tra tetti','Underground routes':'Percorsi sotterranei','City view':'Vista città','Surface':'Superficie','Exact overrides':'Valori esatti','Structure target · 0 = automatic':'Obiettivo edifici · 0 = automatico','Boats · −1 = automatic':'Imbarcazioni · −1 = automatico','Terrain relief (m) · −1 = automatic':'Rilievo del terreno (m) · −1 = automatico',
 'Choose a preset and a size. Everything else is optional.':'Scegli un modello e una dimensione. Tutto il resto è facoltativo.',
 'Terrain, streets and building access are planned before architecture. No people, rumors or generated stories.':'Terreno, strade e accessi vengono pianificati prima dell’architettura. Nessuna persona, voce o storia generata.',
 'HQ changes materials, roof detail and depth, not geometry.':'HQ cambia materiali, dettagli dei tetti e profondità, non la geometria.',
 'Unused land stays open. Exact overrides are placement targets, never permission to overlap water or roads.':'Il terreno inutilizzato resta libero. I valori esatti sono obiettivi di collocazione: non autorizzano sovrapposizioni con acqua o strade.',
 'These are editable route overlays, not interiors or battle maps. Choose the view in Style after generation.':'Sono tracciati modificabili, non interni o mappe di battaglia. Scegli la vista in Stile dopo la generazione.',
 'This layer was not generated. Enable it in City Studio before creating a new map.':'Questo livello non è stato generato. Abilitalo in Studio città prima di creare una nuova mappa.',
 'Surface geometry stays unchanged when switching views.':'La geometria della superficie non cambia passando da una vista all’altra.',
 'Four huts & three boats':'Quattro capanne e tre barche','Imperial capital · Golden River':'Capitale imperiale · Fiume Dorato','Nordic council · hillside harbor':'Consiglio nordico · porto sul pendio','Bridge & market town':'Borgo del ponte e del mercato','Mountain citadel':'Cittadella montana','Lagoon trading port':'Porto mercantile della laguna','Great-tree sanctuary':'Santuario del grande albero','Oasis court city':'Città delle corti nell’oasi','Crater-side arcane city':'Città arcana del cratere','Reclaimed colossus city':'Città rinata del colosso',
 'A tiny fishing landing, not a small city. Exactly four huts and three skiffs at the recommended size.':'Un piccolo approdo, non una città in miniatura. Quattro capanne e tre barche con la dimensione consigliata.',
 'A river metropolis with a naval waterfront, palace precinct, dense old streets and villa gardens.':'Metropoli fluviale con lungofiume navale, palazzo, vicoli fitti e giardini delle ville.',
 'Longhouses and a council hall across sloping terraces, with stairs, a winding ascent and longship berths.':'Case lunghe e sala del consiglio su terrazze in pendio, con scale, salita tortuosa e attracchi per drakkar.',
 'A crossing and fountain square with shops, shared frontages, gardens and a less regular outer edge.':'Un ponte e una piazza con fontana, botteghe, fronti continui, giardini e margini irregolari.',
 'A hilltop stronghold, terrain-routed streets and lower service quarters on buildable slopes.':'Fortezza in cima alla collina, strade adattate al terreno e quartieri di servizio sui pendii edificabili.',
 'Quays and canal crossings frame dense waterside frontages and enclosed merchant courtyards.':'Banchine e ponti sui canali racchiudono fronti densi e corti mercantili.',
 'Woodland neighborhoods and curving paths grow around a protected, monumental tree.':'Quartieri boschivi e sentieri curvi crescono attorno a un albero monumentale protetto.',
 'Flat roofs, shaded lanes, courtyard compounds and palms beside a protected spring basin.':'Tetti piani, vicoli ombrosi, corti e palme accanto a un bacino sorgivo protetto.',
 'Terraced neighborhoods and diverted streets surround a vast, unbuildable impact hollow.':'Quartieri terrazzati e strade deviate circondano un vasto cratere non edificabile.',
 'New streets and gardens sit beside ruined foundations and a monumental fallen relic.':'Strade nuove e giardini affiancano fondazioni in rovina e una reliquia monumentale caduta.',
 'Terrain & access':'Terreno e accessi','Buildings & gardens':'Edifici e giardini','No narrative generation':'Nessuna generazione narrativa','approx. structures':'edifici indicativi','boats':'imbarcazioni'
};
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const choices={climate:[['auto','Climate by architecture'],['temperate','Temperate'],['hot-dry','Hot and dry'],['hot-humid','Hot and humid'],['cold','Cold / snowy']],size:[['recommended','By preset'],['hamlet','Hamlet · a few huts'],['village','Village'],['town','Town'],['city','City'],['capital','Capital']],fabric:[['recommended','By preset'],['organic','Organic growth'],['mixed','Old lanes & planned precincts'],['planned','Planned precincts']],detail:[['quiet','Quiet'],['balanced','Balanced'],['rich','Rich']],landscape:[['recommended','By preset'],['plain','Open plain'],['river','Great river'],['coast','Seacoast'],['fjord','Fjord & slopes'],['hills','Hills & terraces'],['canals','Lagoon & canals'],['forest','Woodland'],['oasis','Oasis basin']],culture:[['recommended','By preset'],['vernacular','Vernacular'],['imperial','Imperial'],['nordic','Nordic timber'],['stone','Mountain stone'],['merchant','Merchant courts'],['woodland','Woodland halls'],['desert','Desert courts'],['arcane','Arcane stone']],wonder:[['recommended','By preset'],['none','No extraordinary landmark'],['great-tree','Great tree'],['crater','Impact crater'],['colossus','Fallen colossus'],['crystal','Crystal spires']],history:[['recommended','By preset'],['none','New settlement'],['old','Old quarter'],['layered','Successive growth'],['ancient','Ancient remains']],walls:[['recommended','By preset'],['none','No walls'],['city','City enclosure'],['citadel','High citadel']],envelope:[['terrain','Terrain-led'],['oval','Strict oval'],['rectangle','Strict rectangle'],['ribbon','Strict elongated form']],fleet:[['recommended','By preset'],['none','No boats'],['fishing','Fishing skiffs'],['trade','Trading vessels'],['armada','Naval armada'],['longships','Longships']]};
const select=(key,title,o)=>`<label>${title}<select data-opt="${key}">${choices[key].map(([v,t])=>`<option value="${v}"${o[key]===v?' selected':''}>${t}</option>`).join('')}</select></label>`;
const check=(key,title,o)=>`<label class="check"><input type="checkbox" data-opt="${key}"${o[key]?' checked':''}>${title}</label>`;
const number=(key,title,o,min,max)=>`<label>${title}<input type="number" data-opt="${key}" min="${min}" max="${max}" step="1" value="${o[key]}"></label>`;
function sections(o){return[
 {id:'settlement',label:'Settlement',html:`<div id="citySummary" class="city-summary" role="status" aria-live="polite"></div>${select('size','Settlement size',o)}${select('fabric','Urban fabric',o)}${select('detail','Visual detail',o)}${check('hq','HQ · detailed materials and lighting',o)}<p class="micro">HQ changes materials, roof detail and depth, not geometry.</p>`},
 {id:'customize',label:'Customize',html:`${select('landscape','Landscape setting',o)}${select('culture','Architectural character',o)}${select('climate','Housing climate',o)}${select('wonder','Fantasy landmark',o)}${select('history','Visible history',o)}${select('walls','Defenses',o)}${select('envelope','Growth boundary',o)}${select('fleet','Waterfront fleet',o)}<details class="city-exact"><summary>Exact overrides</summary>${number('structureCount','Structure target · 0 = automatic',o,0,2400)}${number('boatCount','Boats · −1 = automatic',o,-1,40)}${number('relief','Terrain relief (m) · −1 = automatic',o,-1,300)}<p class="micro">Unused land stays open. Exact overrides are placement targets, never permission to overlap water or roads.</p></details><details class="city-exact"><summary>Optional city layers</summary>${check('rooftops','Rooftop connections',o)}${check('underground','Underground routes',o)}<p class="micro">These are editable route overlays, not interiors or battle maps. Choose the view in Style after generation.</p></details>`}
];}
function update(doc,city,o,t=x=>x){const box=doc.getElementById('citySummary');if(!box)return;const v=city.resolve(o),preset=city.PRESETS.find(p=>p.id===o.preset)||city.PRESETS[0];box.innerHTML=`<span class="eyebrow">${esc(t('Fantasy settlements'))}</span><strong>${esc(t(preset.name))}</strong><p>${esc(t(preset.hint))}</p><div class="city-summary-facts"><span>${v.km} × ${v.km} km</span><span>~${v.count} ${esc(t('approx. structures'))}</span><span>${v.boats} ${esc(t('boats'))}</span></div>`;}
return{sections,update,IT,choices};
});
