/* Presentation-only bilingual map labels. GPL-3.0-only.
 * Canonical saved text and all geometry stay unchanged. Known stock names in
 * older saves are supported; proper names, notes and explicit custom labels
 * are never machine-translated. Renderers can also pass language:'en'/'it'.
 */
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.MegamapMapLabels=api;})(typeof globalThis!=='undefined'?globalThis:this,function(root){
'use strict';
const IT=Object.freeze({
 "Search assets…": "Cerca asset…",
 "Library": "Biblioteca",
 "Alchemy table": "Tavolo alchemico",
 "Ambush point": "Punto d'imboscata",
 "Anchor": "Ancora",
 "Anvil": "Incudine",
 "Approach": "Avvicinamento",
 "Arcane portal": "Portale arcano",
 "Archery range": "Campo di tiro con l'arco",
 "Arena entrance": "Ingresso dell’arena",
 "Armory": "Armeria",
 "Arrow barrel": "Barile di frecce",
 "Arsenal courts": "Corti dell’arsenale",
 "Artisan work yard": "Cortile artigiano",
 "Artisans": "Artigiani",
 "Assembly stone benches": "Sedili dell’assemblea",
 "Assembly terrace": "Terrazza dell’assemblea",
 "Astral observatory dais": "Pedana dell’osservatorio astrale",
 "Astral terraces": "Terrazze astrali",
 "Astronomical court": "Corte astronomica",
 "Bakery": "Panetteria",
 "Ballroom": "Sala da ballo",
 "Banquet table": "Tavolo da banchetto",
 "Bar": "Bancone",
 "Bar counter": "Bancone",
 "Barn roof": "Tetto del fienile",
 "Barracks": "Caserma",
 "Barracks · drill quadrangle": "Caserma · corte di addestramento",
 "Barracks · three halls": "Caserma · tre padiglioni",
 "Barrel": "Barile",
 "Basalt columns": "Colonne di basalto",
 "Bathhouse · pools": "Terme · vasche",
 "Bathing chamber": "Sala da bagno",
 "Battle site": "Sito di battaglia",
 "Beach landing": "Approdo sulla spiaggia",
 "Bed": "Letto",
 "Bedchamber": "Camera da letto",
 "Bedroll": "Sacco a pelo",
 "Bench": "Panca",
 "Birch": "Betulla",
 "Blacksmith": "Fabbro",
 "Boat": "Barca",
 "Boatbuilding cradle": "Culla di costruzione navale",
 "Boatwright yards": "Cantieri dei maestri d’ascia",
 "Bones": "Ossa",
 "Bookshelf": "Scaffale",
 "Botanical collection": "Collezione botanica",
 "Boulder": "Masso",
 "Bramble thicket": "Roveto",
 "Brazier": "Braciere",
 "Bridge": "Ponte",
 "Bridge & market town": "Borgo del ponte e del mercato",
 "Bridge markets": "Mercati dei ponti",
 "Broadleaf woodland stand": "Bosco di latifoglie",
 "Broken column": "Colonna spezzata",
 "Broken roadside cart": "Carro rotto lungo la strada",
 "Bunk bed": "Letto a castello",
 "Burial complex": "Complesso funerario",
 "Bush": "Cespuglio",
 "Cabinet": "Armadio",
 "Camp": "Accampamento",
 "Camp clearing": "Radura del campo",
 "Campaign planning table": "Tavolo di guerra",
 "Caravan camp": "Campo carovaniero",
 "Caravan courts": "Corti carovaniere",
 "Caravan loading court": "Corte di carico carovaniera",
 "Cargo stacks": "Cataste di merci",
 "Cargo weighbridge": "Pesa delle merci",
 "Carved standing stone": "Pietra eretta incisa",
 "Castle": "Castello",
 "Castle interior": "Interno del castello",
 "Cauldron": "Calderone",
 "Cave": "Grotta",
 "Cave entrance marker": "Segnaposto ingresso grotta",
 "Cave mouth": "Bocca della grotta",
 "Cavern": "Caverna",
 "Cedar": "Cedro",
 "Cellar": "Cantina",
 "Cells": "Celle",
 "Cemetery": "Cimitero",
 "Chair": "Sedia",
 "Chapel": "Cappella",
 "Charcoal clamps": "Cataste di carbone",
 "Chess table": "Tavolo da scacchi",
 "Chest": "Baule",
 "Cistern": "Cisterna",
 "Cliff face": "Parete rocciosa",
 "Cloister": "Chiostro",
 "Cloister garden": "Giardino del chiostro",
 "Cloister herb beds": "Aiuole del chiostro",
 "Cloth merchant": "Mercante di stoffe",
 "Coastal cove": "Cala costiera",
 "Coiled rope": "Corda arrotolata",
 "Collapsed hall": "Sala crollata",
 "College · two courts": "Collegio · due corti",
 "Colonnaded court": "Corte colonnata",
 "Common room": "Sala comune",
 "Commons": "Spazi comuni",
 "Communal bread oven": "Forno comune del pane",
 "Compass rose": "Rosa dei venti",
 "Conifer woodland stand": "Bosco di conifere",
 "Cottage": "Casale",
 "Cottage roof": "Tetto del casale",
 "Courtyard": "Corte",
 "Courtyard house": "Casa con corte",
 "Courtyard washing line": "Stendibiancheria del cortile",
 "Covered market halls": "Sale coperte del mercato",
 "Covered wagon": "Carro coperto",
 "Crate": "Cassa",
 "Crater-side arcane city": "Città arcana del cratere",
 "Crop field": "Campo coltivato",
 "Crossing": "Guado",
 "Crossing marker": "Segnaposto attraversamento",
 "Crypt": "Cripta",
 "Crystal": "Cristallo",
 "Crystal grotto": "Grotta di cristalli",
 "Crystal workshops": "Botteghe dei cristalli",
 "Cultivated fringe": "Margine coltivato",
 "Cypress": "Cipresso",
 "Danger marker": "Segnaposto pericolo",
 "Dead Tree": "Albero morto",
 "Deep cavern": "Caverna profonda",
 "Desert wadi": "Uadi del deserto",
 "Dining room": "Sala da pranzo",
 "Display suit of armor": "Armatura da esposizione",
 "Docks": "Banchine",
 "Door": "Porta",
 "Drain junction": "Incrocio di drenaggio",
 "Drawing room": "Salotto",
 "Driftwood tangle": "Intreccio di legname alla deriva",
 "Drill yard": "Piazza d'armi",
 "Dry dock": "Bacino di carenaggio",
 "Dry island": "Isola asciutta",
 "Dune ridge": "Cresta di dune",
 "Dungeon entrance": "Ingresso del dungeon",
 "Dungeon garrison": "Guarnigione sotterranea",
 "Dye vats": "Tini per il colore",
 "Entrance hall": "Sala d'ingresso",
 "Eroded gully": "Canalone eroso",
 "Excavated relic garden": "Giardino dei reperti",
 "Fallen log": "Tronco caduto",
 "Family dwelling": "Abitazione familiare",
 "Far bank": "Riva opposta",
 "Farmsteads": "Fattorie",
 "Fern": "Felce",
 "Fire": "Fuoco",
 "Fireplace": "Camino",
 "Fish drying racks": "Stenditoi per il pesce",
 "Fish market · waterside sheds": "Mercato del pesce · capannoni sul molo",
 "Fishing baskets and net": "Ceste e rete da pesca",
 "Fishing landing": "Approdo di pesca",
 "Fishing net": "Rete da pesca",
 "Fishing net racks": "Rastrelliere per reti",
 "Flag": "Bandiera",
 "Forest road encounter": "Scontro sulla strada nel bosco",
 "Formal parterre": "Parterre formale",
 "Fortified manor": "Maniero fortificato",
 "Fountain": "Fontana",
 "Four huts & three boats": "Quattro capanne e tre barche",
 "Four-poster canopy bed": "Letto a baldacchino",
 "Foyer": "Ingresso",
 "Fumarole": "Fumarola",
 "Gallery": "Galleria",
 "Garden gazebo": "Gazebo da giardino",
 "Garden holdings": "Appezzamenti a giardino",
 "Gardens": "Giardini",
 "Gardens / park": "Giardini / parco",
 "Garrison bunk": "Letto a castello della guarnigione",
 "Garrison courts": "Corti della guarnigione",
 "Garrison supply rack": "Scaffale della guarnigione",
 "Gatehouse": "Corpo di guardia",
 "Glass display cabinet": "Vetrina in vetro",
 "Grain sacks": "Sacchi di grano",
 "Granary · silos": "Granai · silos",
 "Grave rows": "File di tombe",
 "Gravestone": "Lapide",
 "Great hall": "Grande sala",
 "Great-tree sanctuary": "Santuario del grande albero",
 "Greenhouse · glazed roof": "Serra · tetto vetrato",
 "Grove": "Boschetto",
 "Guard post": "Posto di guardia",
 "Guest rooms": "Camere",
 "Guildhall · assembly hall": "Sede della corporazione · sala assembleare",
 "Handcart": "Carretto",
 "Hanging chain": "Catena sospesa",
 "Harbor capstan": "Argano portuale",
 "Harbor crane": "Gru del porto",
 "Harbor exchange": "Mercato portuale",
 "Harpsichord": "Clavicembalo",
 "Hay ricks": "Covoni di fieno",
 "Hedge maze": "Labirinto di siepi",
 "Hedgerow": "Siepe",
 "Heraldic banner stand": "Stendardo araldico",
 "Hidden cache": "Nascondiglio",
 "Hill": "Collina",
 "Hollow bog stump": "Ceppo cavo nella palude",
 "Hospital · ward wings": "Ospedale · ali dei reparti",
 "House": "Casa",
 "Ice shards": "Schegge di ghiaccio",
 "Imperial capital · Golden River": "Capitale imperiale · Fiume Dorato",
 "Industrial quarter": "Quartiere industriale",
 "Inn": "Locanda",
 "Inn · coaching courtyard": "Locanda · corte per le carrozze",
 "Inn · long hall": "Locanda · sala lunga",
 "Inner sanctum": "Santuario interno",
 "Iron cage": "Gabbia di ferro",
 "Iron stove": "Stufa in ferro",
 "Irrigated gardens": "Giardini irrigati",
 "Isolated farmstead marker": "Segnaposto fattoria isolata",
 "Jagged crag": "Roccia frastagliata",
 "Jungle tree": "Albero della giungla",
 "Karst sinkhole": "Dolina carsica",
 "Keep · defensive towers": "Torrione · torri difensive",
 "Kiln and forge yard": "Cortile di forno e forgia",
 "Kiln yard": "Cortile delle fornaci",
 "Kitchen": "Cucina",
 "L-shaped roof": "Tetto a L",
 "Lagoon trading port": "Porto mercantile della laguna",
 "Lair": "Tana",
 "Lantern": "Lanterna",
 "Lava field": "Campo di lava",
 "Library · reading wings": "Biblioteca · ali di lettura",
 "Lighthouse": "Faro",
 "Lily pads": "Ninfee",
 "Livestock paddocks": "Recinti per il bestiame",
 "Living cave system": "Sistema di caverne abitate",
 "Longhouse clusters": "Gruppi di case lunghe",
 "Longhouse roof": "Tetto a casa lunga",
 "Longship": "Drakkar",
 "Longship landing": "Approdo dei drakkar",
 "Loom": "Telaio",
 "Loose scree fan": "Ghiaione",
 "Manor house": "Casa padronale",
 "Mansion interior": "Interno della dimora",
 "Marble bathtub": "Vasca in marmo",
 "Market": "Mercato",
 "Market frontages": "Fronti del mercato",
 "Market stall": "Bancarella",
 "Marsh causeway": "Passerella nella palude",
 "Marsh grass tussock": "Ciuffo d’erba palustre",
 "Marsh pool": "Stagno paludoso",
 "Master bedchamber": "Camera padronale",
 "Mausoleum · vaulted tomb": "Mausoleo · tomba a volta",
 "Meadow patch": "Macchia di prato",
 "Memorial circle": "Cerchio commemorativo",
 "Memorial gardens": "Giardini commemorativi",
 "Merchant balance": "Bilancia del mercante",
 "Merchant courts": "Corti mercantili",
 "Merchant trade court": "Corte commerciale dei mercanti",
 "Merchants": "Mercanti",
 "Mesa": "Mesa",
 "Mess hall": "Sala mensa",
 "Military quarter": "Quartiere militare",
 "Military supply yard": "Deposito militare",
 "Mill": "Mulino",
 "Mill · wheel and loft": "Mulino · ruota e solaio",
 "Mine": "Miniera",
 "Mixed homes": "Abitazioni miste",
 "Modest homes": "Abitazioni modeste",
 "Monastery · cloister": "Monastero · chiostro",
 "Monastic cells": "Celle monastiche",
 "Moss and lichen": "Muschio e licheni",
 "Mountain": "Montagna",
 "Mountain citadel": "Cittadella montana",
 "Mountain path": "Sentiero di montagna",
 "Mushroom": "Fungo",
 "Narthex": "Nartece",
 "Natural arch": "Arco naturale",
 "Naval yards": "Cantieri navali",
 "Nave": "Navata",
 "Necropolis": "Necropoli",
 "Noble quarter": "Quartiere nobiliare",
 "Nordic council · hillside harbor": "Consiglio nordico · porto sul pendio",
 "Oak": "Quercia",
 "Oasis court city": "Città delle corti nell’oasi",
 "Obelisk": "Obelisco",
 "Objective": "Obiettivo",
 "Observatory": "Osservatorio",
 "Observatory · dome and annex": "Osservatorio · cupola e annesso",
 "Octagonal cistern": "Cisterna ottagonale",
 "Old mixed quarter": "Quartiere antico misto",
 "Old river quarter": "Quartiere fluviale antico",
 "Old ruins": "Vecchie rovine",
 "Old timber lanes": "Antichi vicoli di legno",
 "Old town": "Città vecchia",
 "Open pit": "Fossa aperta",
 "Opposing entrance": "Ingresso opposto",
 "Orchard": "Frutteto",
 "Orchard block": "Isolato di frutteto",
 "Ornamental carpet": "Tappeto ornamentale",
 "Outfall": "Scolo",
 "Palace · four corner towers": "Palazzo · quattro torri angolari",
 "Palace-side villas": "Ville presso il palazzo",
 "Palisade": "Palizzata",
 "Palm": "Palma",
 "Pantry": "Dispensa",
 "Passing ledge": "Cengia di passaggio",
 "Paved neighborhood square": "Piazza lastricata di quartiere",
 "Pavilion tent": "Tenda padiglione",
 "Pine": "Pino",
 "Pond garden": "Giardino con laghetto",
 "Pool": "Vasca",
 "Portcullis": "Saracinesca",
 "Portcullis assembly": "Saracinesca",
 "Pottery · kiln annex": "Ceramica · annesso con fornace",
 "Processional court": "Corte processionale",
 "Produce stall": "Bancarella di ortaggi",
 "Quest marker": "Segnaposto missione",
 "Rack": "Rastrelliera",
 "Raft": "Zattera",
 "Reclaimed colossus city": "Città rinata del colosso",
 "Reed bed": "Canneto",
 "Reeds": "Canneto",
 "Reflecting pool": "Vasca riflettente",
 "Reliquary": "Reliquiario",
 "Residential lanes": "Vicoli residenziali",
 "Rim-side lanes": "Vicoli sul bordo",
 "Ritual altar": "Altare rituale",
 "Ritual circle": "Cerchio rituale",
 "River crossing": "Guado fluviale",
 "Roadside clearing": "Radura lungo la strada",
 "Roadside inn": "Locanda sulla strada",
 "Rock": "Roccia",
 "Rock cluster": "Gruppo di rocce",
 "Rock outcrop": "Affioramento roccioso",
 "Rocky ridge spur": "Sperone roccioso",
 "Root sanctuary": "Santuario delle radici",
 "Rope safety railing": "Parapetto di corda",
 "Rope-making yard": "Corderia all’aperto",
 "Round column": "Colonna rotonda",
 "Round table": "Tavolo rotondo",
 "Round tower roof": "Tetto della torre rotonda",
 "Rowhouses · four terraces": "Case in fila · quattro schiere",
 "Royal bedchamber": "Camera reale",
 "Ruin": "Rovina",
 "Rune stone": "Pietra runica",
 "Sacred grove gardens": "Giardini del bosco sacro",
 "Saguaro cactus": "Cactus saguaro",
 "Sailboat": "Barca a vela",
 "Salt pan": "Salina",
 "Sanctuary gardens": "Giardini del santuario",
 "Sanctum": "Santuario",
 "Sand dunes": "Dune di sabbia",
 "Sarcophagus": "Sarcofago",
 "Scholars": "Studiosi",
 "Scholars’ courts": "Corti degli studiosi",
 "Scrap and salvage": "Rottami e recuperi",
 "Scree slope": "Pendio di ghiaia",
 "Sea stack": "Faraglione",
 "Secret marker": "Segnaposto segreto",
 "Servants": "Servitù",
 "Service and kiln yards": "Cortili di servizio e forni",
 "Set banquet table": "Tavolo da banchetto apparecchiato",
 "Shaded bazaar": "Bazar ombreggiato",
 "Shaded market stalls": "Bancarelle coperte",
 "Shanty · patched roof": "Baracca · tetto rattoppato",
 "Shantytown": "Baraccopoli",
 "Shipwreck": "Relitto",
 "Shipyard · boat shed": "Cantiere navale · rimessa per barche",
 "Shop · street awning": "Negozio · tenda da strada",
 "Shops · covered arcade": "Negozi · portico coperto",
 "Shrine": "Sacello",
 "Shrine · small sanctuary": "Santuario · piccolo sacello",
 "Signpost": "Cartello",
 "Skull": "Teschio",
 "Smithy · forge chimney": "Fucina · camino della forgia",
 "Snowfield": "Campo di neve",
 "Spider web": "Ragnatela",
 "Spike trap": "Trappola a punte",
 "Spreading oak canopy": "Chioma di quercia",
 "Spring sanctuary": "Santuario della sorgente",
 "Spring source": "Sorgente",
 "Stable": "Scuderia",
 "Stable · stalls and paddock": "Scuderia · box e recinto",
 "Stacked cut timber": "Catasta di legname",
 "Stairs": "Scale",
 "Statue": "Statua",
 "Stone circle": "Cerchio di pietre",
 "Stone fire ring": "Anello di pietre per il fuoco",
 "Storeroom": "Magazzino",
 "Street lantern": "Lanterna di strada",
 "Street well · top down": "Pozzo di strada · dall'alto",
 "Striped market canopy": "Tendone a righe del mercato",
 "Study": "Studio",
 "Sunken crypt entrance": "Ingresso della cripta sprofondata",
 "Table": "Tavolo",
 "Tavern · L-shaped hall": "Osteria · sala a L",
 "Temple": "Tempio",
 "Temple precinct": "Area dei templi",
 "Temple roof": "Tetto del tempio",
 "Temple · central dome": "Tempio · cupola centrale",
 "Tenement · rear court": "Caseggiato · corte posteriore",
 "Tent": "Tenda",
 "Thatched hut": "Capanna di paglia",
 "Throne": "Trono",
 "Throne and stepped dais": "Trono su pedana",
 "Throne room": "Sala del trono",
 "Tidal boulder cluster": "Gruppo di scogli",
 "Timber boardwalk section": "Tratto di passerella in legno",
 "Timber storage rack": "Rastrelliera per legname",
 "Tower": "Torre",
 "Townhouse · narrow gable": "Casa a schiera · timpano stretto",
 "Townhouse · twin gables": "Casa a schiera · doppio timpano",
 "Trail cairn": "Ometto di pietre",
 "Trailhead": "Inizio del sentiero",
 "Training ring": "Anello di addestramento",
 "Treasure pile": "Pila di tesori",
 "Tree": "Albero",
 "Tree stump": "Ceppo",
 "Undercity waterworks": "Impianti idrici sotterranei",
 "Upholstered chaise longue": "Chaise-longue imbottita",
 "Vault": "Caveau",
 "Vegetable beds": "Aiuole di ortaggi",
 "Vestry": "Sagrestia",
 "Villa · pool court": "Villa · corte con piscina",
 "Villa · walled courtyard": "Villa · corte murata",
 "Villas / wealthy homes": "Ville / abitazioni benestanti",
 "Vine pergola": "Pergolato di vite",
 "Volcano": "Vulcano",
 "Wall torch": "Torcia a muro",
 "War room": "Sala di guerra",
 "Warehouse": "Magazzino",
 "Warehouse · loading apron": "Magazzino · piazzale di carico",
 "Warehouse · twin sheds": "Magazzino · due capannoni",
 "Washroom": "Lavatoio",
 "Washroom / privy": "Lavatoio / latrina",
 "Watch post": "Posto di guardia",
 "Waterfall": "Cascata",
 "Waterlogged tree trunk": "Tronco sommerso",
 "Watermill": "Mulino ad acqua",
 "Waypoint": "Punto di passaggio",
 "Weapon rack": "Rastrelliera per armi",
 "Well": "Pozzo",
 "Wildflowers": "Fiori di campo",
 "Willow": "Salice",
 "Wooden jetty": "Pontile di legno",
 "Woodland halls": "Sale del bosco",
 "Working monastery": "Monastero abitato",
 "Working waterfront": "Lungomare operativo",
 "Workshop": "Officina",
 "Workshop and service yards": "Cortili di botteghe e servizi",
 "Workshop · sawtooth shed": "Bottega · tetto a denti di sega",
 "Woven rug": "Tappeto intrecciato",
 "Wrecked fishing skiff": "Barca da pesca naufragata",
 "Writing desk": "Scrivania",
 "Golden River": "Fiume Dorato",
 "Fountain square": "Piazza della fontana",
 "Imperial palace": "Palazzo imperiale",
 "Council terrace": "Terrazza del consiglio",
 "Council hall": "Sala del consiglio",
 "High keep": "Rocca alta",
 "Monument precinct": "Area monumentale",
 "Spring basin": "Bacino sorgivo",
 "Villa gardens": "Giardini delle ville",
 "Outer lanes": "Vicoli periferici",
 "Residence": "Abitazione",
 "Shop": "Bottega",
 "Storehouse": "Deposito",
 "Old Town": "Città vecchia",
 "Noble": "Nobile",
 "East gate": "Porta orientale",
 "South gate": "Porta meridionale",
 "West gate": "Porta occidentale",
 "North gate": "Porta settentrionale",
 "East Gate": "Porta orientale",
 "South Gate": "Porta meridionale",
 "West Gate": "Porta occidentale",
 "North Gate": "Porta settentrionale",
 "Guardroom": "Corpo di guardia",
 "Hall": "Sala",
 "Archive": "Archivio",
 "Entrance": "Ingresso",
 "Guildhall": "Sede della gilda",
 "Tenement": "Caseggiato",
 "Townhouse": "Casa a schiera",
 "Shack": "Baracca",
 "Villa": "Villa",
 "Palace": "Palazzo",
 "Smithy": "Fucina",
 "Tavern": "Taverna",
 "Monastery": "Monastero",
 "Barrack": "Caserma",
 "Keep": "Rocca",
 "College": "Collegio",
 "Hospital": "Ospedale",
 "Bathhouse": "Terme",
 "Barn": "Fienile",
 "Granary": "Granaio",
 "Fish market": "Mercato del pesce",
 "Shipyard": "Cantiere navale",
 "Greenhouse": "Serra",
 "Mausoleum": "Mausoleo",
 "Unassigned": "Non assegnato",
 "Cache": "Nascondiglio",
 "Junction": "Bivio",
 "Ruins": "Rovine",
 "Painted river town · temperate": "Borgo fluviale dipinto · temperato",
 "Painted river town · hot and dry": "Borgo fluviale dipinto · caldo e secco",
 "house": "Casa",
 "townhouse": "Casa a schiera",
 "tenement": "Caseggiato",
 "shack": "Baracca",
 "villa": "Villa",
 "palace": "Palazzo",
 "workshop": "Bottega artigiana",
 "smithy": "Fucina",
 "shop": "Bottega",
 "warehouse": "Magazzino",
 "inn": "Locanda",
 "tavern": "Taverna",
 "temple": "Tempio",
 "shrine": "Santuario",
 "monastery": "Monastero",
 "barracks": "Caserma",
 "keep": "Rocca",
 "stable": "Scuderia",
 "library": "Biblioteca",
 "college": "Collegio",
 "observatory": "Osservatorio",
 "hospital": "Ospedale",
 "bathhouse": "Terme",
 "mill": "Mulino",
 "barn": "Fienile",
 "granary": "Granaio",
 "guildhall": "Sede della gilda",
 "fishmarket": "Mercato del pesce",
 "shipyard": "Cantiere navale",
 "greenhouse": "Serra",
 "mausoleum": "Mausoleo",
 "council-hall": "Sala del consiglio",
 "gable": "A due falde",
 "hip": "A padiglione",
 "flat": "Piano",
 "longhouse": "Casa lunga",
 "legacy": "Classico",
 "tile": "Tegole",
 "slate": "Ardesia",
 "shingle": "Scandole",
 "thatch": "Paglia",
 "turf": "Zolle erbose",
 "plaster": "Intonaco",
 "weathered": "Invecchiato",
 "Top-down": "Dall’alto",
 "2.5D view (Shift+V)": "Vista 2.5D (Maiusc+V)",
 "2.5D preview": "Anteprima 2.5D",
 "Keep label as written": "Mantieni l’etichetta come scritta",
 "Building type": "Tipo di edificio",
 "Custom label": "Etichetta personalizzata",
 "Read-only axonometric city view. Building heights and terrain are schematic; edit the authoritative top-down map.": "Vista assonometrica della città di sola lettura. Le altezze degli edifici e del terreno sono schematiche; modifica la mappa dall’alto.",
 "North": "Nord",
 "East": "Est",
 "South": "Sud",
 "West": "Ovest",
 "Seed": "Seme",
 "No map notes.": "Nessuna nota sulla mappa.",
 "GM ONLY": "SOLO GM",
 "GM COPY — CONTAINS SECRETS": "COPIA GM — CONTIENE SEGRETI",
 "Megamap GM gazetteer": "Gazzettiere GM di Megamap",
 "region": "Regione",
 "local": "Regione locale",
 "city": "città",
 "battle": "Battaglia",
 "fantasy": "Studio città",
 "The painted plan contains no usable buildable district.": "La pianta dipinta non contiene quartieri edificabili utilizzabili.",
 "City": "Città",
 " selected": " selezionati",
 "settlement": "insediamento",
 "river": "fiume",
 "HQ · detailed materials and lighting": "HQ · materiali dettagliati e illuminazione",
 "Housing climate": "Clima delle abitazioni",
 "Climate by architecture": "Clima secondo l’architettura",
 "Temperate": "Temperato",
 "Hot and dry": "Caldo e secco",
 "Hot and humid": "Caldo e umido",
 "Cold / snowy": "Freddo / nevoso",
 "City Studio": "Studio città",
 "City · legacy": "Città · classica",
 "Fantasy settlements": "Insediamenti fantasy",
 "Settlement": "Insediamento",
 "Customize": "Personalizza",
 "Settlement size": "Dimensione dell’insediamento",
 "By preset": "Secondo il modello",
 "Hamlet · a few huts": "Borgata · poche capanne",
 "Village": "Villaggio",
 "Town": "Borgo",
 "Capital": "Capitale",
 "Urban fabric": "Tessuto urbano",
 "Organic growth": "Crescita organica",
 "Old lanes & planned precincts": "Vicoli antichi e quartieri pianificati",
 "Planned precincts": "Quartieri pianificati",
 "Visual detail": "Dettaglio visivo",
 "Quiet": "Sobrio",
 "Balanced": "Equilibrato",
 "Rich": "Ricco",
 "Landscape setting": "Contesto geografico",
 "Open plain": "Pianura aperta",
 "Great river": "Grande fiume",
 "Seacoast": "Costa marina",
 "Fjord & slopes": "Fiordo e pendii",
 "Hills & terraces": "Colline e terrazze",
 "Lagoon & canals": "Laguna e canali",
 "Woodland": "Bosco",
 "Oasis basin": "Bacino dell’oasi",
 "Architectural character": "Carattere architettonico",
 "Vernacular": "Tradizionale",
 "Imperial": "Imperiale",
 "Nordic timber": "Legno nordico",
 "Mountain stone": "Pietra montana",
 "Desert courts": "Corti del deserto",
 "Arcane stone": "Pietra arcana",
 "Fantasy landmark": "Monumento fantasy",
 "No extraordinary landmark": "Nessun monumento straordinario",
 "Great tree": "Grande albero",
 "Impact crater": "Cratere d’impatto",
 "Fallen colossus": "Colosso caduto",
 "Crystal spires": "Guglie di cristallo",
 "Visible history": "Storia visibile",
 "New settlement": "Insediamento nuovo",
 "Old quarter": "Quartiere antico",
 "Successive growth": "Crescita stratificata",
 "Ancient remains": "Resti antichi",
 "Defenses": "Difese",
 "No walls": "Senza mura",
 "City enclosure": "Cinta cittadina",
 "High citadel": "Cittadella alta",
 "Growth boundary": "Limite di crescita",
 "Terrain-led": "Secondo il terreno",
 "Strict oval": "Ovale vincolante",
 "Strict rectangle": "Rettangolo vincolante",
 "Strict elongated form": "Forma allungata vincolante",
 "Waterfront fleet": "Flotta sul lungomare",
 "No boats": "Senza imbarcazioni",
 "Fishing skiffs": "Barche da pesca",
 "Trading vessels": "Navi mercantili",
 "Naval armada": "Armata navale",
 "Longships": "Drakkar",
 "Optional city layers": "Livelli città facoltativi",
 "Rooftop connections": "Collegamenti tra tetti",
 "Underground routes": "Percorsi sotterranei",
 "City view": "Vista città",
 "Surface": "Superficie",
 "Exact overrides": "Valori esatti",
 "Structure target · 0 = automatic": "Obiettivo edifici · 0 = automatico",
 "Boats · −1 = automatic": "Imbarcazioni · −1 = automatico",
 "Terrain relief (m) · −1 = automatic": "Rilievo del terreno (m) · −1 = automatico",
 "Choose a preset and a size. Everything else is optional.": "Scegli un modello e una dimensione. Tutto il resto è facoltativo.",
 "Terrain, streets and building access are planned before architecture. No people, rumors or generated stories.": "Terreno, strade e accessi vengono pianificati prima dell’architettura. Nessuna persona, voce o storia generata.",
 "HQ changes materials, roof detail and depth, not geometry.": "HQ cambia materiali, dettagli dei tetti e profondità, non la geometria.",
 "Unused land stays open. Exact overrides are placement targets, never permission to overlap water or roads.": "Il terreno inutilizzato resta libero. I valori esatti sono obiettivi di collocazione: non autorizzano sovrapposizioni con acqua o strade.",
 "These are editable route overlays, not interiors or battle maps. Choose the view in Style after generation.": "Sono tracciati modificabili, non interni o mappe di battaglia. Scegli la vista in Stile dopo la generazione.",
 "This layer was not generated. Enable it in City Studio before creating a new map.": "Questo livello non è stato generato. Abilitalo in Studio città prima di creare una nuova mappa.",
 "Surface geometry stays unchanged when switching views.": "La geometria della superficie non cambia passando da una vista all’altra.",
 "A tiny fishing landing, not a small city. Exactly four huts and three skiffs at the recommended size.": "Un piccolo approdo, non una città in miniatura. Quattro capanne e tre barche con la dimensione consigliata.",
 "A river metropolis with a naval waterfront, palace precinct, dense old streets and villa gardens.": "Metropoli fluviale con lungofiume navale, palazzo, vicoli fitti e giardini delle ville.",
 "Longhouses and a council hall across sloping terraces, with stairs, a winding ascent and longship berths.": "Case lunghe e sala del consiglio su terrazze in pendio, con scale, salita tortuosa e attracchi per drakkar.",
 "A crossing and fountain square with shops, shared frontages, gardens and a less regular outer edge.": "Un ponte e una piazza con fontana, botteghe, fronti continui, giardini e margini irregolari.",
 "A hilltop stronghold, terrain-routed streets and lower service quarters on buildable slopes.": "Fortezza in cima alla collina, strade adattate al terreno e quartieri di servizio sui pendii edificabili.",
 "Quays and canal crossings frame dense waterside frontages and enclosed merchant courtyards.": "Banchine e ponti sui canali racchiudono fronti densi e corti mercantili.",
 "Woodland neighborhoods and curving paths grow around a protected, monumental tree.": "Quartieri boschivi e sentieri curvi crescono attorno a un albero monumentale protetto.",
 "Flat roofs, shaded lanes, courtyard compounds and palms beside a protected spring basin.": "Tetti piani, vicoli ombrosi, corti e palme accanto a un bacino sorgivo protetto.",
 "Terraced neighborhoods and diverted streets surround a vast, unbuildable impact hollow.": "Quartieri terrazzati e strade deviate circondano un vasto cratere non edificabile.",
 "New streets and gardens sit beside ruined foundations and a monumental fallen relic.": "Strade nuove e giardini affiancano fondazioni in rovina e una reliquia monumentale caduta.",
 "Terrain & access": "Terreno e accessi",
 "Buildings & gardens": "Edifici e giardini",
 "No narrative generation": "Nessuna generazione narrativa",
 "approx. structures": "edifici indicativi",
 "boats": "imbarcazioni",
 "building": "edificio",
 "road": "strada",
 "asset": "asset",
 "High garrison": "Guarnigione alta",
 "Lower forge terraces": "Terrazze basse delle forge",
 "Slope-side houses": "Case sul pendio",
 "Upper stone courts": "Corti alte di pietra",
 "Quay warehouses": "Magazzini delle banchine",
 "Canal trading courts": "Corti commerciali dei canali",
 "Canalside lanes": "Vicoli dei canali",
 "Reclaimed foundations": "Fondazioni recuperate",
 "Relic gardens": "Giardini dei reperti",
 "Stonecutters’ yards": "Cortili degli scalpellini",
 "City details": "Dettagli città",
 "Road": "Strada",
 "River": "Fiume",
 "Wall": "Muro",
 "Terrain": "Terreno",
 "buildings": "edifici",
 "label": "etichetta",
 "Paint a city plan": "Dipingi una pianta urbana",
 "Use my painted plan": "Usa la mia pianta dipinta",
 "Districts": "Quartieri",
 "Routes and walls": "Strade e mura",
 "Sea / lake": "Mare / lago",
 "Military": "Militare",
 "Industry": "Industria",
 "Public square": "Piazza pubblica",
 "Brush size": "Dimensione pennello",
 "Paint": "Dipingi",
 "Erase this layer": "Cancella questo livello",
 "Undo stroke": "Annulla tratto",
 "Redo stroke": "Ripeti tratto",
 "Clear plan": "Svuota pianta",
 "Example plan": "Pianta di esempio",
 "Load current map plan": "Carica la pianta della mappa",
 "Preview city": "Anteprima città",
 "Back to painting": "Torna a dipingere",
 "Generating preview…": "Generazione anteprima…",
 "Painted plan canvas": "Tela della pianta dipinta",
 "Plan disabled; the selected preset will generate normally.": "Pianta disabilitata; il modello selezionato verrà generato normalmente.",
 "Paint districts where you want buildings. River and sea override district paint. Unpainted land stays open. Roads across short water gaps become bridges; roads crossing walls create gates.": "Dipingi i quartieri dove vuoi gli edifici. Fiume e mare prevalgono sui quartieri. Il terreno non dipinto resta libero. Le strade su brevi tratti d’acqua diventano ponti; le strade che attraversano le mura creano porte.",
 "Choose a labeled brush, then drag. Eraser affects only the selected brush layer. Keyboard: arrows move the cursor, Space paints, Ctrl/Cmd+Z undoes.": "Scegli un pennello etichettato e trascina. La gomma agisce solo sul livello del pennello scelto. Tastiera: frecce per muovere il cursore, Spazio per dipingere, Ctrl/Cmd+Z per annullare.",
 "Draft retained when you go Back or change presets. It is not used by sidebar generation.": "La bozza resta tornando Indietro o cambiando modello. Non viene usata dalla generazione laterale.",
 "Clear all painted strokes?": "Cancellare tutti i tratti dipinti?",
 "Replace the draft with the example plan?": "Sostituire la bozza con la pianta di esempio?",
 "Paint at least one buildable district before generating.": "Dipingi almeno un quartiere edificabile prima di generare.",
 "strokes": "tratti",
 "No plan on the current map.": "La mappa attuale non ha una pianta dipinta.",
 "Plan limits reached. Erase or simplify the draft.": "Limiti della pianta raggiunti. Cancella o semplifica la bozza.",
 "Preview uses the current preset, size and climate; it does not add a map.": "L’anteprima usa modello, dimensione e clima attuali; non aggiunge una mappa.",
 "Canvas unavailable": "Canvas non disponibile",
 "2.5D city preview": "Anteprima città 2.5D",
 "Open 2.5D view": "Apri vista 2.5D",
 "Read-only perspective. Edit the top-down map.": "Prospettiva di sola lettura. Modifica la mappa dall’alto.",
 "Rotate left": "Ruota a sinistra",
 "Rotate right": "Ruota a destra",
 "Fit view": "Adatta vista",
 "Export 2.5D SVG": "Esporta SVG 2.5D",
 "Export 2.5D PNG": "Esporta PNG 2.5D",
 "Back to map": "Torna alla mappa",
 "2.5D city viewport": "Area di visualizzazione città 2.5D",
 "Drag to pan; scroll or +/− to zoom; arrow keys pan; Home fits.": "Trascina per spostare; scorri o usa +/− per lo zoom; le frecce spostano; Home adatta.",
 "Schematic terrain and building heights. No geometry is changed.": "Terreno e altezze degli edifici schematici. La geometria non cambia.",
 "Preparing image…": "Preparazione immagine…",
 "Image exported.": "Immagine esportata.",
 "The image could not be exported. Try SVG instead.": "Impossibile esportare l’immagine. Prova il formato SVG.",
 "district": "quartiere",
 "wall": "muro",
 "poi": "punto d'interesse",
 "room": "stanza",
 "image": "immagine",
 "paint": "pittura",
 "portal": "porta",
 "light": "luce",
 "Building program: ": "Programma edilizio: ",
 " · roof: ": " · tetto: ",
 "No navigable water: the requested boats were not placed.": "Nessuna acqua navigabile: le imbarcazioni richieste non sono state collocate.",
 "Neighborhood regeneration kept protected objects and left constrained plots open.": "La rigenerazione del quartiere ha conservato gli oggetti protetti e lasciato liberi i lotti vincolati.",
 "A painted road enters open water or exceeds the 180 m bridge limit; that wet section was left open.": "Una strada dipinta entra in acqua aperta o supera il limite di 180 m per i ponti; quel tratto d’acqua è rimasto libero.",
 "A small painted district could not fit a usable street.": "Un piccolo quartiere dipinto non ha spazio per una strada utilizzabile.",
 "Invalid painted city plan.": "Pianta urbana dipinta non valida.",
 "Unknown city brush.": "Pennello urbano sconosciuto.",
 "Invalid city brush stroke.": "Tratto del pennello urbano non valido.",
 "City plan is too detailed; simplify the sketch.": "La pianta urbana è troppo dettagliata; semplifica lo schizzo.",
 "Invalid city brush coordinates.": "Coordinate del pennello urbano non valide.",
 "Too many disconnected districts (maximum 48). Join or erase small patches.": "Troppi quartieri separati (massimo 48). Unisci o cancella le zone più piccole.",
 "Not a City Studio map.": "Non è una mappa di Studio città.",
 "Select a City Studio neighborhood.": "Seleziona un quartiere di Studio città.",
 "Unlock the neighborhood first.": "Sblocca prima il quartiere.",
 "Unknown neighborhood program.": "Programma del quartiere sconosciuto.",
 "2.5D preview requires a City Studio map.": "L’anteprima 2.5D richiede una mappa di Studio città.",
 "Invalid custom title flag.": "Impostazione del titolo personalizzato non valida.",
 "Invalid custom label flag.": "Impostazione dell’etichetta personalizzata non valida.",
 " · mean ": " · media ",
 " · relief ": " · dislivello ",
 "Export failed: ": "Esportazione non riuscita: ",
 "VTT export failed: ": "Esportazione VTT non riuscita: ",
 "Generation failed: ": "Generazione non riuscita: ",
 "Could not open atlas: ": "Impossibile aprire l'atlante: ",
 "Startup failed: ": "Avvio non riuscito: ",
 "Local recovery was invalid: ": "Il recupero locale non è valido: ",
 "Edit exceeds document limits: ": "La modifica supera i limiti del documento: ",
 "Could not regenerate this quarter: ": "Impossibile rigenerare questo quartiere: ",
 "Application error: ": "Errore dell'applicazione: ",
 "Atlas full: ": "Atlante pieno: ",
 "Atlas limit: ": "Limite dell'atlante: ",
 "Combined atlas exceeds ": "L'atlante combinato supera ",
 "Ground elevation: ": "Quota del suolo: ",
 "Approx. ": "Circa ",
 " inhabitants. The linked city is generated separately, not a seamless zoom.": " abitanti. La città collegata è generata separatamente, non è uno zoom continuo.",
 " for removal": " per la rimozione",
 "Remove ": "Rimuovi ",
 " selected · Shift-click to add": " selezionati · Maiusc-clic per aggiungere",
 " of ": " di ",
 " assets": " asset",
 " objects": " oggetti",
 " buildings": " edifici",
 " cells": " celle",
 " samples": " campioni",
 " m spacing": " m di spaziatura",
 " synthetic elevations.": " quote sintetiche.",
 " map created. Use the tools to make it yours.": " mappa creata. Usa gli strumenti per renderla tua.",
 " is unsupported in this browser. Export PNG instead.": " non è supportato in questo browser. Esporta in PNG.",
 " exported: ": " esportato: ",
 "Generating ": "Generazione ",
 " map…": " mappa…",
 "Preview unavailable: ": "Anteprima non disponibile: ",
 "Add at least ": "Aggiungi almeno ",
 " points first.": " punti prima.",
 " objects removed.": " oggetti rimossi.",
 "Rendering ": "Rendering ",
 " · GRID CELLS": " · CELLE GRIGLIA",
 " m elevation": " m di quota",
 "Straight-line distance: ": "Distanza in linea retta: ",
 " · hidden": " · nascosto",
 " · locked": " · bloccato",
 "VTT exported: ": "VTT esportato: ",
 " walls, ": " muri, ",
 " doors, ": " porte, ",
 " lights. Verify in your importer.": " luci. Verifica nel tuo importatore.",
 "Select ": "Seleziona ",
 " updated.": " aggiornato.",
 " maps. Open the Atlas panel to remove a map, or start a new atlas.": " mappe. Apri il pannello Atlante per rimuovere una mappa, oppure inizia un nuovo atlante.",
 " maps. Remove a map here, or start a new atlas — save a backup first.": " mappe. Rimuovi una mappa qui, oppure inizia un nuovo atlante — salva prima un backup.",
 " selected map": " mappa selezionata",
 " selected maps": " mappe selezionate",
 " from the atlas? This cannot be undone.": " dall'atlante? L'operazione non è reversibile."
});
const has=k=>Object.prototype.hasOwnProperty.call(IT,k);
function language(view={}){return view.language==='en'||view.language==='it'?view.language:root.MegamapI18n?.getLang?.()==='it'?'it':'en';}
function text(value,lang=language()){
 if(typeof value!=='string'||lang!=='it'||!value||value.length>512)return value;
 if(has(value))return IT[value];
 let m;
 if((m=value.match(/^Only (\d+) of (\d+) requested boats fit safely in navigable water\.$/)))return `Solo ${m[1]} delle ${m[2]} imbarcazioni richieste trovano posto in sicurezza nelle acque navigabili.`;
 if((m=value.match(/^Placed (\d+) of (\d+) requested structures; unsuitable or inaccessible plots were left open\.$/)))return `Collocati ${m[1]} dei ${m[2]} edifici richiesti; i lotti inadatti o inaccessibili sono rimasti liberi.`;
 if((m=value.match(/^The sketch has (\d+) disconnected street groups\. Paint connecting roads and bridge\/gate crossings to join them\.$/)))return `Lo schizzo contiene ${m[1]} gruppi di strade separati. Disegna strade di collegamento e attraversamenti con ponti o porte per unirli.`;
 if((m=value.match(/^No buildings fit (.+) patch (\d+); enlarge it or add a road\.$/)))return `Nessun edificio entra nella zona ${m[2]} (${text(m[1],lang)}); ampliala o aggiungi una strada.`;

 // Only structured stock labels, not arbitrary word-by-word translation.
 const numbered=value.match(/^(\d+\s*[.·-]\s*|)(.+?)(\s+\d+)?$/);
 if(numbered&&has(numbered[2]))return numbered[1]+IT[numbered[2]]+(numbered[3]||'');
 const copy=value.match(/^(.*) \(copy\)$/);if(copy&&has(copy[1]))return IT[copy[1]]+' (copia)';
 const landmark=value.match(/^(Hidden|Silent|Lost|Forgotten|Broken|Old) (Shrine|Mine|Cavern|Camp|Watch|Barrows)$/);
 if(landmark){const adj={Hidden:'nascosto',Silent:'silenzioso',Lost:'perduto',Forgotten:'dimenticato',Broken:'in rovina',Old:'antico'},noun={Shrine:'Santuario',Mine:'Miniera',Cavern:'Caverna',Camp:'Accampamento',Watch:'Posto di guardia',Barrows:'Tumuli'};let a=adj[landmark[1]];if(['Mine','Cavern'].includes(landmark[2])&&a.endsWith('o'))a=a.slice(0,-1)+'a';if(landmark[2]==='Barrows'&&a.endsWith('o'))a=a.slice(0,-1)+'i';return noun[landmark[2]]+' '+a;}
 const cave=value.match(/^(Cold|Deep|Echoing|Hidden|Split|Wind) Cave (\d+)$/);
 if(cave)return ({Cold:'Grotta fredda',Deep:'Grotta profonda',Echoing:'Grotta degli echi',Hidden:'Grotta nascosta',Split:'Grotta spaccata',Wind:'Grotta del vento'})[cave[1]]+' '+cave[2];
 return value;
}
function feature(f,lang=language()){return f?.labelCustom||f?.type==='label'?f?.label||'':text(f?.label||'',lang);}
function title(s,lang=language()){return s?.titleCustom?s.title:text(s?.title||'',lang);}
function kind(f,lang=language()){const id=f?.buildingKind||f?.cityRoof||f?.type||'';const en={fishmarket:'Fish market','council-hall':'Council hall',gable:'Gabled',hip:'Hipped',flat:'Flat',longhouse:'Longhouse',legacy:'Legacy'}[id]||id.charAt(0).toUpperCase()+id.slice(1);return lang==='it'?text(id,lang):en;}
function scene(s,lang=language()){
 if(lang!=='it')return s;
 return {...s,title:title(s,lang),features:s.features.map(f=>{const label=feature(f,lang);return label===f.label?f:{...f,label};})};
}
return{IT,language,text,feature,title,kind,scene};
});
